import {useState} from 'react';
import './style.css'

export default function Journal(props) {
    const [day1, setDay1] = useState(false);
    const [day2, setDay2] = useState(false);
    const [day3, setDay3] = useState(false);
    const [day4, setDay4] = useState(false);
    const [day5, setDay5] = useState(false);
    const [day6, setDay6] = useState(false);
    const [day7, setDay7] = useState(false);
    const [day8, setDay8]   = useState(false);
    const [day9, setDay9] = useState(false);
    const [day10, setDay10] = useState(false);
    const [day11, setDay11] = useState(false);
    const [day12, setDay12] = useState(false);
    const [day13, setDay13] = useState(false);
    const [day14, setDay14] = useState(false);
    const [day15, setDay15] = useState(false);


    function expandDay1() {
        setDay1(!day1);
    }

    function expandDay2() {
        setDay2(!day2);
    }

    function expandDay3() {
        setDay3(!day3);
    }

    function expandDay4() {
        setDay4(!day4);
    }

    function expandDay5() {
        setDay5(!day5);
    }

    function expandDay6() {
        setDay6(!day6);
    }

    function expandDay7() {
        setDay7(!day7);
    }

    function expandDay8() {
        setDay8(!day8);
    }

    function expandDay9() {
        setDay9(!day9);
    }

    function expandDay10() {
        setDay10(!day10);
    }

    function expandDay11() {
        setDay11(!day11);
    }

    function expandDay12() {
        setDay12(!day12);
    }

    function expandDay13() {   
        setDay13(!day13);
    }

    function expandDay14() {
        setDay14(!day14);
    }

    function expandDay15() {
        setDay15(!day15);
    }

    function back() {
        props.setTripChosen(false);
        props.setTrip('');
    }
    
    return (
        <div>

            <h2 style={{marginTop: '5vh'}}>Japan, 2024</h2>
            <h3 style={{marginBottom: '5vh'}}>Travel journal</h3>

            <div id="expand">
                <div onClick={expandDay1} id="day1ExpanderMorJpn" className="headings">
                    <h4 className="dayHeader">Day 1</h4>
                    <h5 className="dayLocation">Shibuya City, Tokyo</h5>
                </div>

                {day1 &&
                    <div className="days" id="day1">
                        <p>If there was one thing Steph and I both knew going into 2024, it was that we needed a major holiday. We'd had a great time in Morocco back in '23, one small earthquake aside, but we had two crucial ingredients that we'd lacked before; a joint income and enough of a stable routine to plan out leave.</p>
                        <p>Of course, thanks to my company's less than stellar leave allowance, this was never going to be a massive three week holiday like America 2022. It would be a two weeker, but it was going to be massive in terms  of the adventure. Nowhere in Europe or nearby like North Africa. It would have to be transcontinental, and our selections were quickly narrowed down.</p>
                        <p>America, this time the Deep South, was a possibility - but leaving only two years between American trips naturally may have made things less special. India was another possibility, particularly some of the northern cities: Jaipur, Agra, Delhi. At the same time, Japan had been very much on the list for both of us for some time. I'd had my reservations when I was younger, but with the benefit of age those all seemed quite silly, and it was clear that Japan would be a holiday of a lifetime.</p>                    
                        <p>Our initial plan had been to fly to Seoul - much cheaper than Tokyo - then get a ferry across after a few days exploring South Korea. But once we looked at it for more than a few moments, it was clear that while there are ferry routes between Seoul and Japan, it only takes you to the very southern tip of Japan, which wasn't great logistically. That's not the only reason; in even a brief look at a Japanese travel itinerary, it was clear that there would be enough in Japan - even Tokyo - to cover even an extended holiday, so it would make much more sense to devote the holiday to Japan and go to South Korea another time.</p>
                        <p>After a brief browse of multi-city journeys we decided that a simple return flight from Tokyo was the easiest way to go. Japan's such an amazing place as far as public transport is concerned, including the legendary <i>Shinkansen</i> - the bullet train. This would allow us quick passage to Kyoto, the cultural capital and one of the must-sees in any trip of Japan. We had one more key destination in mind too, the northern island of Hokkaido, a vast open space with some of the best scenery in the world. It turned out that wasn't so easy on the Bullet Train, so we booked an internal flight from Osaka nearby Kyoto.</p>
                        <p>And so it was that after months of planning that we ended up at Gatwick on an unseasonably chilly morning. We'd stayed the night at 8 Shirley Road the night before and had aimed for as little sleep as possible to get some sleep on the plane. Terence had driven us to East Croydon, which I hate to go through when coming back from a holiday but love coming out from because it reminds me of everything we leave behind when we go away.</p>
                        <p>We got to Gatwick early, and not just because this was an important flight. Steph had recently signed up to an AMEX Gold card, meaning access to all sorts of cool VIP airport lounges. We made a beeline for the lounge as soon as we dropped off the hold luggage, and were soon greeted with an option that was definitely more luxurious than waiting in a departure lounge, but would be a teensy bit overshadowed by the VIP lounges we enountered later. There was breakfast food - the classic staples you get everywhere in England - bacon, sausages, eggs, and a few generic croissaints and pastries. There was also the drink. The airport seems to be the only place where you can rock up at 8am and be clamouring for a pint. We had a few drinks at the (predictably way too regulated) bar then head to our gate.</p>
                        <p>It was a long flight - eleven hours - but it didn't feel insane. Steph slept for a fair bit of it, and I slept for at least half an hour. We were flying with China Eastern and their film selection was abysmal compared to pretty much anyone else we'd been with and after trying to watch Aquaman and The Flash I settled on Sorry We Missed You, a grim northern portrayal of zero hour contracts in Newcastle.</p>
                        <p>We were stopping off in Shanghai for three hours, which we'd reasoned would be long enough, and it would have been - if it wasn't for a gate change that completely blindsided us. We arrived in a section that seemed completely empty and as Steph was freshening up a guy came shouting about a flight to Haneda. I called out after him, but it looked like it was an earlier than our flight. That's what I thought - turns out it was more of a communication error.</p>
                        <p>Cut to about twenty minutes later and we realised that we were not only in the wrong departure lounge, the right one was on the whole opposite side of the airport. We asked the same guy who'd been shouting for Haneda Airport before and he told us - through extensive use of a translation app - that the gate had already closed. Keeping the panic attacks at bay, we went back to the security gate and went through everything again while the staff expressed their exasperation with us. We got onto a later flight for free, which was great, and everything seemed to have worked out - except one tragic detail. We'd been booked into the 5.30 slot of the Dawn Avatar Robot Cafe, an awesome cafe and restaruant where you get served by robots! We were looking forward to it as an introduction to the fantastic weirdness of Tokyo, but we were now automatically too late.</p>
                        <p>We did have one consolation prize, however. The VIP lounge in Shanghai made the Gatwick lounge look like a Wetherspoons. It looked like the kind of place where you'd do a GQ photoshoot. The place had a sleek, professional look, with great food - bao buns, Chinese delicacies - and drinks - plentiful beers, wines and spirits - being generously replenished. As we sat there enjoying this luxury we reflected that this wasn't the bad start we thought it was.</p>
                        <p>We boarded the next flight and before long we were landing at Haneda Airport. We were full of excitement as we went through the airport, got our hold luggage that had been delayed for us, and headed towards the underground, where we'd be heading to Shibuya.</p>
                        <p>Shibuya is a great entry point into Tokyo. Firstly, you've got everything that you'll see later on - constant neon, a busy train station, lots of bars and restaurants. But Shibuya doesn't get the same intense number of tourists as the other Tokyo cities, so it can be walked and navigated without being too overwhelmed.</p>
                        <p>After an (unsurprisingly quiet!) train ride that carried us through quiet Japanese towns and open countryside all the way into the the big city! From there, it was a shorter journey to Shibuya Station, one of the major stations in Tokyo and quite probably the world. Stepping off of the platform into the main station will stay with both of us for a very long time. It's an insane, unfathomably busy, place with a million different people and types of people. Navigating it is no easy feat. We took around half an hour to find the right exit, finally getting out and towards the hotel. Going to street level was like walking into Blade Runner. The street was swathed in bright neon lights from the tops of the tall skyscrapers to the shops that lined the road. It was like stepping into a different world, one we'd seen in pictures and films before but looked even more out there in real life.</p>
                        <p>Despite the otherworldness, we noticed something as we walked. Shibuya, in a way that's quite unique to Tokyo but that it has in common with Sapporo, looks like an American city - specifically Las Vegas. It has insanely wide roads and is lined with overpasses that see plenty of traffic. We crossed one of these to get to our hotel, and from the top, we got a startling view. The two of us had a palpable "Damn, we're finally here!" moment that wasn't even slighly diminished by our long journey. </p>
                        <p>We found the hotel after a quick look arouund, and it was a nice, clean place - although the room, and especially the bathroom, was a bit small. We were tired after the long journey but also hungry, so we headed back to near the station in search of some food. We found a delicious sushi place and started our Japanese culinary experience with some sushi. Then we headed back and showered, ready to sleep off our travels. </p>
                        <p></p>
                        </div>}

                    <div onClick={expandDay2} id="day2ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 2</h4>
                        <h5 className="dayLocation">Ginza City, Tokyo</h5>
                    </div>f

                    {day2 &&
                    <div className="days" id="day2">    f
                        <p>We awoke to pouring rain the next morning, itching to start exploring. We'd both slept well without much in the way of jetlag, which was a result considering that we'd gone about as far east as it was possible to go in this odd marble. Today we were going southeast, to Tokyo Harbour and Ginza City. We were going to start our day at the world-famous Toyuso Fish Market right in the heart of the harbour. We grabbed some breakfast at the hotel - it was mostly pastries, but they had fairly okay coffee and - result for me - what I now assume to be authentic Hokkaido milk based on the taste. We headed out and got drenched within a few minutes in the heavy rain. We headed to a nearby 7-11 and bought rain ponchos, a move I'd have normally objected to on a fashion basis, but the rain was intense.</p>
                        <p>Cut to horror a few minutes later when we realised we were the only two people in the whole of Shibuya wearing the things, and that they definitely made us look like <i>baka gaijin</i>. We huddled in them until the station, dripping wet all over the Ginza line all the way to the harbour. We had a short walk to Toyuso proper.</p>
                        <p>Toyuso is so distinctly Tokyo that I'm surprised it isn't featured on more of the tourist ads. It's a couple of solid square miles of tightly-packed streets and tented market stall, with tourists and locals clamouring for the delicious food. There was every kind of seafood a person could imagine, including favourites that the top fishmonger at Billingsgate wouldn't have been able to identify. Most it it was being sold for instant eating purposes; there was a trades fish market there but it was clearly overshadowed by the masses of food stalls. We went along, helping ourselves to everything, but the star of the show was a delicious king crab leg that could only be described as 'roughly human-sized'. The flavour was absolutely indescribable, buttery (without any actual butter) and glorious. We had a few more bites after that, ranging in beautiful strangeness from wagyu on a stick to matcha soda ice cream float.</p>
                        <p>Once we'd eaten our fill, it was time to head out to our first proper booked activity - TeamLabs Planets in nearby Ginza. It was one of things I got most excited about when booking up Japan, and I think I spread my enthusiasm to Steph. It's a cutting-edge, ultra-cool modern art exhibition run by an artistic collective. And if you're thinking that sounds boring, you'd be right - if this was a standard modern art exhibition and not one of the coolest man-made things you'll ever see in your lifetime. It's an extreme show of colour, light, and spectacle that you really won't see anywhere else in the world.</p>
                        <p>We arrived and were filed into a locker room where we took our shoes and socks off. That's not just a Japanese thing - as soon as we got through our feet got submerged in water that flowed as we walked through to the exhibits. The first large room we entered - and it looked incomparably large, though with the extensive mirrors it was probably not too much bigger than a tennis court. This was the LED forest - a room with a thousand LED tendrils descending from the ceiling, sending out bright light patterns that are incredible to look at. We found a space to sit - more like lay down to take everything in - and stared at the incredible display. It was dazzling experience and we were already giddy when it came to the next room. As soon as we walked in, we were confronted with gigantic balls. That's not the start of a traumatic experience, that is literally what it means - huge, person sized bouncing balls that change colour every few seconds and can be explored in about every way a person could think of - bounced on, jumped against, and climbed. It wasn't as visually stunning as the LED forest but it was a phenomenal experience.</p>
                        <p>We got back into water before the next room, and unlike before it got deeper instead of more shallow. We came out into a place that took our breath away - a vibrant pond made with nothing but light. LED reeds and vegetation swayed in an imaginary wind and holographic rainbow trout in every conceivable colour 'swam' around us with calm abandon. The whole thing was such an immense headrush and it only intensified when we realised that the reeds and the fish adapted to movement in a way nothing else thus far had. The reeds stuck to me wherever I moved, and the fish wriggled away when you put a hand or a foot near them. It was utterly amazing, only marred by the fact that I got a jolt of fear every time I took my phone out. If I dropped it mid-snap or put it back in my pocket in a way that it could easily fall out, it would plunge into the murky depths, instantly becoming both brickified by the water and lost forever in the murky depths.</p>
                        <p>We headed out after a little while and went through a few smaller rooms, most of which were physical experiences rather than light shows - floor that felt like quicksand, walls you could bounce off, that sort of thing. We started to wonder how TeamLabs would top the trout pond when we walked into a room that melted our brains.</p>
                        <p>It was another large dark room, this time with no mirrors. At first, the central feature of the room just looked like a lightshow - then we looked up and saw one of the coolest things either of us had ever seen. It was an artificial sky of colours, vibrant flowers and foliage, and fascinating patterns. It was moving across from one side of the room to the other, and while the logical side of my brain knew that the lightshow was moving and not the room, you instantly got absorbed in this notion that you were on a spinning plane, hurtling through a universe that smiled down at us benevolently. We lay there for what was probably only about fifteen minutes but could have just as easily been hours.</p>
                        <p>The next section was the garden, the only outdoor area. The rain had stopped so we went out without our hideous ponchos or an umbrella - which, this being Japan, was free - into a lush open air area that was covered in these strange, almost Easter Island-looking statues, but in miniature and without faces, and translucent plastic. They all played a different sound when you moved them, which was really cool - but everything naturally paled in comparison to what we'd seen inside. The next area came slighlty closer, though; it was a garden that was completely full of vibrant, beautiful flowers that descended from a trellis. We had to slide on our backs to go through the room without touching them, which was a weird experience but was very worth it as we stared up at the beautiful bouquets.</p>
                        <p>That was the last little bit of the tour, and we headed out, awed by all the amazing things we'd seen. The rain had started up again but only as a light trickle, which was fine because we only had a short walk before the bus to our next destination, Akihabara Electric Town. Akihabara is one of the most distinctive areas of Tokyo, and even Japan. It's the very epicenter of everything related to anime, manga, video and card games, and geek culture. It's also the place to find all sorts of bizarre and cutting edge electronics that you'd never find in the UK. We got a bus then subway over to the area and headed out. As soon as we did, we took in the wonders of the place. Like what we'd seen of Tokyo so far, every building was swathed in displays and posters bombarding passers-by, but unlike Shibuya or Shinjuku, it's very specified towards the core geek products. We looked around and saw massive department stores full of smaller stores probably selling everything you could imagine, huge comic emporiums, and to my delight, amusement arcades.</p>
                        <p>First, though, we had to eat. We were both starving after our breakfast of delicious crab all those hours ago. We stopped in at a place not far from the subway station that looked cool and authentic and sat in a small, stuffy but nice place with grills on the table. We picked out a beef dish and cooked it gently on the grill, wolfing it down hungrily. Most of the people there looked like otaku - basically an ultrageek - but it was a cool, quirkly little place and we enjoyed our meat dish.</p>
                        <p>We went into a department store first, a place that was multiple stories tall. There was a toy shop that had these amazingly detailed figures based on anime and games, and I seem to recall recognising a few figures from Final Fantasy VII - pretty much my only foray into Japanese gaming. Upstairs there was a trading card place that was small was but absolutely jampacked with different trading card games, from Pokemon to Yu-Gi-Oh, the former of which Steph and I had talked about quite a bit in the leadup to the trip, and the latter Steph had barely heard of but gave me such an immense rush of nostalgia; I hadn't thought of it in years, but I really enjoyed the show, and I got flashbacks of printing off online copies of the cards with Patrick and cutting them out so we could duel. We looked around and went further up, seeing a whole library's worth of manga.</p>
                        <p>There were more floors, but they were less cutesy and innocent. All of the floors above this one were more adult, and while I won't go into detail, almost all of it was devoted to schoolgirls. It's one part of Japanese culture that I don't particularly like, and while there's a lot worse in the world, it made me feel a bit queazy whenever I saw a group of happy, cheerful schoolgirls afterwards knowing that there were grown men somewhere that were way too interested in them.</p>
                        <p>After we left the department store, we went to go find more places to shop - and saw something that at least Steph had been interested in trying out - a Maid Cafe. Maid Cafes are part of that same unsavoury cultural element that produced some of the stuff we'd seen on the top floors of that department store. They're not as bad as Host and Hostess Cafes - a grimly exploitative enterprise designed to drain obscene amounts of cash by basically convincing lonely people they're in a relationship. They're fairly straightforward cafes except that your servers are all 18 (and probably younger) year old girls. One of the things Akihabara is famous for is its cosplay maid cafes, where the girls dress up like anime characters.</p>
                        <p>We had no idea what the girl outside was dressed as, but I agreed with some hesitation - its's not a good look. James May refused to go into one outright when he was in Japan, but Steph was still keen. We agreed we'd look around for the best one once our appetites picked back up after our barbecue lunch, especially once we saw the photos of the menu and our stomachs turned. The food was meant to be 'kawaii' - a Japanese word that could be basically summed up as 'ineffably cute' - but it was disgusting beyond all measure. First there was a 'burger bear' a grotesque cartoony bear face made out of ground beef with disgusting, overcooked-looking vegetables. The next was a lasagne that looked like it wouldn't have passed quality control for Tesco ready meals with some kanji lettering squired onto it in ketchup. I'm a visual eater and it particularly turned my stomach.</p>
                        <p>As we walked, we saw more anime girls handing out flyers, and as Steph hates any form of social interaction I was the one to grab flyers, something that made me look like a real creep. We didn't come across one that we liked, though we did at least go into one of the Maid Cafes later in the holiday - and we didn't like it one bit. Instead, we went to an electronic supermarket, the kind of place where you can buy anything. the problem was that as very little of it was in English, this was restricted to things that we actually visually understood, like keyboards. They had an amazing array of computer keyboards, all of which looked amazing and stylish, but the price - they averaged around £70 - and the fact that the keys were in Japanese put me off. After we'd had our fill shopping electronics, it was time to hit the arcades.</p>
                        <p>Akihabara is the global hub of arcades, and that was music to our ears. I'm a seasoned arcade game lover who first felt the bug playing House of the Dead near Bognor Regis pier when I was probably not too much older than Leo is, and while Steph's a bit of a neophyte when it comes to arcades, she was keen to try them out.</p>
                        <p>The first place we went to was by Bandai, creators of Bandai Namcoworld in the Trocadero in London. It had about six floors of arcade games, all of them brilliant. Our first spot was the Dance Dance Revolution machine, which for reasons I'll never understand (space?) are never a mainstay of seaside arcades. Consequently I haven't played one since my teens, and I was itching to show Steph the ropes. Despite being terribly uncoordinated at it when I'd tried it out when I was younger, I was actually really good at it. Steph was too, but I scraped a win. We went through all six floors, trying out classics either neither of us had heard of or which I'd long forgotten. But it was getting late, and we were getting hungry. We headed out, and my prevailing memory of the place was an old grandmother beaming with delight and recording her grandson playing some game I can't remember. It was a nice little reminder that Akihabara aws just as much for family fun as it was the seedy stuff we'd seen earlier.</p>
                        <p>We were headed over to Chuo-dori, Ginza's most famous restaurant street. We walked around, checking out the restaurants at both ends of the street. The rain had intensified, but it wasn't the worst thing in the world; a rainy night in Tokyo may be an unpleasant sweaty mess but the rain and the neon gives the city an amazing noirish feel. We decided to stop at a place that looked popular and it had a ticket system, so we had to shelter from the rain for about ten minutes. We had a few different dishes - sashimi, crab salad, and a few more uttery delicious dishes that we enjoyed. We sat at the counter and had a lot of communication with our chef, which allowed me to try out some of the Japanese phrases I'd learned when it comes to food. At the start of the meal you say 'itadakimasu', pronounced 'itadakimass' - which means 'thank you for the feast'. If the meal was excellent, and this one was, you say 'gochiso samedishida' which means 'it was a feast!' The chef seemed delighted that we knew it, and even more delighted when I asked in probably butchered but honest Japanese if we could take photographs.</p>
                        <p>We didn't want the night to be over just then, and we'd seen a karaoke place down the road. Turns out, we didn't quite understand Tokyo's concept of multistorey entertainment and headed straight in the direction of the first bar we saw, being ushered in by two cheerful promoter types. It wasn't until we ordered a drink that I actually asked about karaoke, and the answer was no, so we left the cost of two beers and one small cover charge lighter. There was a karaoke place, but we weren't sure how to get to it, and there was another karaoke place down the road - Big Echo.</p>
                        <p>It wasn't the raucous karaoke bar experience we'd been expecting, but was instead a karaoke booth that you rented by the hour. The main area looked like a classy yet empty late night bar and the booths were nice and comfy. We paid for an hour and dove in, singing some of our favourite karaoke tunes from Vampire Weekend, OutKast, and Rush (me) and Beyonce, Rihanna and Credence Clearwater (Steph, that complex lass). We had a whale of a time, but the hour went way too quick. We headed back to the hotel, still enjoying the look of Tokyo in the rain, showered and slept.</p>  
                    </div>}

                    <div onClick={expandDay3} id="day3ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 3</h4>
                        <h5 className="dayLocation">Asakusa City, Tokyo</h5>
                    </div>

                    {day3 &&
                    <div className="days" id="day3">
                        <p>We woke up the next morning to glorious sunshine, replacing the grim weather of yesterday. Unfortunately, that wasn't the only thing I woke up to; I had a sore, scratchy throat. At first I thought it was just the aircon (I always get a sore throat with strong air conditioning) but it proved to be something different entirely - but more on that later.</p>
                        <p>This morning we were headed over to Senso-Ji, probably the most famous Shinto shrine in Japan (or anywhere really because it doesn't really exist outside of Japan and her diaspora) and one of Tokyo's must-sees. We took a quick trip on the subway and got there without much hassle. Steph, normally my equal when it came to navigation, had really taken the lead here. Only her phone was able to use an eSim, so she was able to get directions up, but she took charge when it came to getting us around, me only occasionally providing observational support when she was too short to see a particular sign.</p>
                        <p>The area around Senso-Ji is of the Edo period and is very well-preserved; not as well-preserved as Kyoto, but very pretty. The only thing that belied that prettiness was the absolute solid mass of crowd. Nowhere we'd seen so far had this many people and it was quite jarring. I have some slightly agoraphobic moments, and Steph is small so she couldn't hide in the clouds like I can. </p>
                        <p>We headed towards the template and saw the Hōzōmon Gate, an ornate entryway into the temple's central concourse. Once we were through we were on a wide tiled pathway with the main temple, impressive and vast, straight ahead of us. You got this immense sense of how ancient the thing was and how many people must have been inspired by its beauty and its majesty. They may have had a bit more solitude to ponder it than we had in the present, but it was still an incredible site. The temple didn't have an accessible interior but it was incredible to look at all the same, and we wandered the grounds and the surrounding gardens with a sense of peace and fulfillment that wasn't affected even slightly by the masses of people, the heat, or my quickly-developing sore throat.</p>
                        <p>Once we'd had our fill of serene and beautiful green spaces we had to get on the move for another grand Japanese cultural tradition - Sumo! We had a Sumo wrestling event booked at midday over on the other side of Asakusa, and we were excited. It was a whole event with a hotpot meal and unlimited fried chicken, as well as a geisha before the actual fight. There were lots of added extras too, like several photo ops (complimentary photo included) and an opportunity to wrestle one of the fighters. We got there in good time and took our seats. It was a surprisingly large arena with about four tiers of seats and an actual fighting ring probably only a bit smaller than a boxing ring. We took our seats and got tucked into a beer, fried chicken, and our hotpot, as well as a pancake dish that you also see in sushi. Japanese fried chicken is just different to the rest of the world, I can't really explain it. The batter is a lot thinner than what you find elsewhere to the extent that it's more like a glaze than a full deep fry. The taste is immense. You pick up these amazing hints of lemon and subtle spices that you'd never find in an English supermarket.</p>
                        <p>The hotpot was amazing too, a hearty broth with strong, meaty flavours that soothed my throat slightly and was extremely moreish. Before long, the announcer came out and introduced the show. He was an American of around fifty years old and he'd been living in Japan for quite a few years. When communicating with the geisha, the wrestlers and the local audience members his Japanese seemed very strong, and you could see he had a passion for the place. If I had to define his entertainment style I would call it less-sleazy Seinfeld meets less-sleazy Brett Gelman (not that either of those men are particularly sleazy, well, not that Gelman isn't) but he had a very similar easy comedic style. The first act that he announced was the geisha, and she came out - kimono, facepaint, the works - and did a traditional dance. It was really cool to see. Many people misunderstand geishas and think it's some sort of escort service - it isn't. These women are meant to be the guardians of culture and refinement in an age where it's no longer the norm. Of course, outsiders - and even customers - don't always see it that way but that's their fault.</p>
                        <p>The dance was very engaging and the geisha was obviously very practiced. She used her fan; fan positioning is everything to a geisha and the angle is meant to be a form of communication all of its own. Once the dance was over, the geisha took photos with the crowd then headed out and the two fighters came out. It was amazing; these guys were right out of what the brain jumped to when it said the word 'Sumo'. One of the guys looked at least 20 stone, and while he was a big guy, a big chunk of it was muscle. The other guy was slightly slimmer and taller but still a huge guy in both senses of the word. They started off with a few light spars, throwing huge chunks of salt into the ring to purify it. There was so much of the stuff that I honestly believe that if I were to eat the sand, it would taste delicious. We got given fun guides on how to cheer the guys on then they came out for the proper match.</p>
                        <p>It was an impressive display. These guys were retired Sumo wrestlers, but they still had a lot of skill, and while there was alot of showboating and showmanship, you could tell that they were still skilled pros. It wasn't exactly UFC, but even though it had less technicality it was still more ancient and ultimately more interesting.</p>
                        <p>The smaller guy won after a short but engaging conflict, and we cheered him on enthusiastically even though he represented the other side of the room. Once the match was done, it was time for members of the audience to challenge their choice of wrestler. I'd originally thought about doing this myself, but I didn't feel it as much for now. I was feeling slightly off; my throat was really bad, and I felt a bit tired and bothered. For another, I was worried that I would struggle to get my defence up and he'd floor me in a couple of seconds. I also had a fear that I consider pretty bizarre in hindsight; it was that I'd try to use my legs to take him out, Judo-style, and accidentally slice his calf with my jagged toenails or something. A few people came up, including, adorably, a girl who couldn't have been older than five. The only person who came up that I thought might have had a shot was an Australian guy who had come here with his partner and a couple of friends. He had a lot of raw power behind his physique; the kind of physique that generally represents hardcore strength, more so than the pro wrestler body type.</p>
                        <p>The competitors came out wearing novelty Sumo costumes and took on their choice of wrestler. The guys toyed with them to the delight of the crowd, making thme think that they were winning before they took them out. The little girl was the cutest fight. Then the Aussie guy came out and his chosen wrestler, I think it was the biggest guy, kinda scaled back the theatrics, recognising him as someone that could actually pose a threat. As it turned out, the Aussie guy won - it was a hard fight, but he got the better of the seasoned pro. It was a fun time all in all, and we were able to stick around for a while and take photos with the guys and the geisha. THey were quite friendly and easygoing, and seemed to love what they did even though they weren't part of the tournament scene anymore. On our way out we got talking to the American host, who turned out to be an amazing font of knowledge about Tokyo. He told us about Harajuku, one of the coolest counterculture and fashion districts of Tokyo, and we were keen to go.</p>
                        <p>We were next headed to the Tokyo National Museum, but first, our American friend told us about a major shopping area nearby. We went there and found a large department store with about five different floors of groceries. Steph was delighted to see that they had Japanese peaches, the most mouthwatering variant, as well as Muscat grapes. We bought these and a few more snacks for us as well as some beginner souvenirs, putting them in the bag and taking the subway over to the museum.</p>
                        <p>The museum is in a grand complex in the middle of a quiet, leafy corner of Taito City. It had the clasic Japanese architecutural design, looking very similar to Senso-Ji except in its muted colours. We dropped our bags off and headed in the two directions I was most itching to visit: armour and katanas. It feels terribly reductionist to boil the most interesting parts of Japanese history to these two objects but they are so very cool. Most of the katanas were presented for the pure quality of the blade over the design of the hilt; it was only the blade that was on show. On the one hand it's the accompanyments - the distinctive hilt, the ornamental scabbard - that at least partially make the katana as cool as it is, but these were some of the best blades in the world, and even a layman like me could see the craftsmanship in the rolled steel. The armour, though, was a different matter entirely. It was an all-mod-cons affair, and you saw the entire set, including mask and all the small details that we recognised from watching Shogun. It was all amazing, but there was one problem - we were already exhausted. The sun had beaten down on us all day, and more to the point we were taking turns at carrying a bag that was now very heavy. Furthermore, I was definitely getting some weird achy feelings along with my throat.</p>
                        <p>We checked out a couple more sections then headed outside, cooling down with a drink from a vending machine. Tonight we would be heading to Shibuya Scramble Crossing, one of the most famous intersections in the world if famous intersections are actually really a thing. We decided to drop the heavy bag off at the room first since the crossing was only ten minutes walk from us, and it immediately felt like the pressure was off. We headed off in that direction, finding it much easier to walk.</p>
                        <p>There are a few words I can associate with Shibuya Scramble Crossing: Hectic; amazing; chaotic. But none of them describe it as well as the word <i>sonder</i>. This word, created by a linguist called John Koenig, can be defined as "the feeling one has on realizing that every other individual one sees has a life as full and real as one’s own, in which they are the central character and others, including oneself, have secondary or insignificant roles". I first heard this word a few years back and loved it, but I'd never seen as good of an example of it until we got to Shibuya Scramble Crossing. Thousands of people making the same track. Everyone of them with a complex net of friends and family, none of whom either of us would ever meet and each of them having their own complex net of friends and family that most probably no one waiting at the same crossing will ever meet or even pass by, despite the fact that they live in the same city. It's fairly mind blowing. Every few minutes, no more than five between, people do this same crossing, waiting patiently as cars speed past before taking control of the crossing, streaming across as a single human wave.</p>
                        <p>We headed up to a Starbucks that Steph's friend Hong had recommended as a great viewing platform, but the queue was miles long and the best viewing point was only for paying customers. Of course, we snuck in anyway, but we didn't stay long. Instead we decided to head to the upper floors of the large building that the Starbucks was in, and I'm very glad we did. The immediate upper floor was some sort of executive lounge for people wanting to catch up on work - and eat and drink for an hour or more for a flat rate. The rate was generous and we took a seat directly overlooking the crosing.</p>
                        <p> The food and drink was great, very similar to the airport lounge in Shanghai with spirits generously laid out, as well as a fridge full of niche beers, sakes and wine. The food was amazing too, and came in hot and cold vareities. We grabbed a drink first, drinking quickly - but responsibly - to get our money's worth before tucking into the gorgeous food. They had microwaveable food like burgers and buns, as well as lots of other snacks. We ate our fill, watching the people go by. There was something truly magical about it - the only exception was the wannabe influencer types who got obsessed with making content as they crossed. They took their time, being in the middle of the road when everyone else was crossing, and narrowly avoiding being hit by cars. The cars, for their part, were out to kill; I think anyone who regularly drove through Scramble Crossing was so fed up of TikTok idiots that vehicular homicide would be a favourable alternative to being held up.</p>
                        <p>We finished our hour but the night was young. We were looking for drinks and karaoke again, but not the booth format of Big Echo; an actual public karaoke bar, where Japanese businessmen caroused their colleagues with drink renditions of Tom Jones. Steph found a place only about a twenty minute walk away.</p>
                        <p>It was a random place, tucked neatly in a complex that looked like a block of flats. The bar itself was tiny, probably only a little bit bigger than our living room - and completey deserted. The barman was the only person there, and that would remain the same throughout the night. I imagined that they would have killed it on a weekend, but even a tiny karaoke bar in Tokyo should see a roaring trade, and we talked - discreetly - about how many nights were as deserted as this, and how they could afford to stay open. We took full advantage of the karaoke mics, singing some of our favourites from last night as well as lots more. With our time unrestricted, we found ourselves much more willing to sing more out there, difficult songs, as well as ones over the five minute mark like <i>Jesus of Suburbia</i>. I felt guilty for subjecting the guy to our noise but Steph rightfully pointed out that we were buying drinks and it didn't really matter anyway as our noise would be nothing compared to a busier night.</p>
                        <p>Unfortunately, that guilt wasn't the only thing I started to feel. The sore throat now made every sip of beer hurt, and I was getting all sorts of weird feelings: muscle pain, coldness, and a burning forehead along with it. I prayed that this was just me fighting some sort of nasty bug and that I'd be right as rain tomorrow, but soon Steph noticed something was wrong and I mentioned I wasn't feeling well.</p>
                        <p>We headed home - it was around 1am and the streets were still bustling. I was shivering even though it wasn't that cold. I collapsed into bed, hoping that a good sleep would sort me out.</p>
                    </div>}

                    <div onClick={expandDay4} id="day4ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 4</h4>
                        <h5 className="dayLocation">Sumida City, Tokyo</h5>
                    </div>

                    {day4 &&
                    <div className="days" id="day4">
                        <p>A good sleep didn't sort me out.</p>
                        <p>I woke up feeling pain in every muscle in my body. My nose and throat were completey blocked up and I felt utterly, completely dreadful. Steph - who'd quite reasonably thought that my illness may have been in my head, given how I am about things - immediately saw how bad things were. My face had badly puffed up and every word from out of my mouth sounded like a death rattle. I relayed the sad news - there was absolutey no way I could leave the bed. I stood up even and got intense vertigo before I'd even taken a step. Steph tried to gently coax me out but knew it was a lost cause, but I insisted that she shouldn't lose a day of holiday because of me. We had a reservation at Tokyo Skytree, an observation deck with amazing views of Tokyo, at seven that evening and I vowed that after a day of sleeping I'd be ready to do that, albeit wearing a mask throughout in the likely event that I was contageous.</p>
                        <p>So I settled back down and Steph headed out. First, she headed to the nearby pharmacy and bought some meds for me, being helped out by a nice lady on the checkout despite the obvious language barrier. Following that, she headed into a coffee shop and grabbed a matcha latte for me and an orange juice for herself - she was slightly hungover, as was I in addition to the illness. She kindly dropped them back to me before heading out, walking from Shibuya to nearby Harajuku.</p>
                        <p>Harajuku is the fashion capital of Tokyo. It's one of the most stylish areas and it's a central congregating point for young, fashionable teens. Steph got there in twenty minutes and started to look around, window shopping at the boutiques and beauty salons before going into Takeshita Street. Despite the scatalogical name, Takeshita is a must see for incredible thrift store deals. It was bustling and busy, even matching levels of Senso-Ji the day before. She went into a beauty salon and checked out all the beautify essentials, buying a facemask as well as a powder designed to cool you down. She kept walking down the long street, checking out some of the souvenir shops. She brought the majority of our friends and family souvenirs there, a massive check off the list. </p>
                        <p>After exploring Takeshita, she got on the subway over to central Tokyo, where the Imperial Palace was waiting. I'd been keen to visit this but our American friend at the Sumo club had dampened our enthusiasm by pointing out that you can't go inside. She explored the gardens, walking around and taking in their beauty. They had an amazing sense of scale and tranquility to them, but there wasn't much to do there apart from walk around and look at the palace from afar. She went to go check out Tokyo Tower, an Eiffel-like structure that finds its way ont every landscape photo of the city. It was very impressive to look at. You could get very close to the base of the tower, touching the girders and walking around unrestricted. It was very big and grand, stretching far into the sky. There was an observation deck to visit but there wasn't enough time, so she sat on a bench and looked up at it. She drank some ginseng - for energy - drink that she bought in Harajuku and took in the sights.</p>
                        <p>She also bought some delicious strawberries, then headed back to the room via bus. She got back about half four, letting me know in advance so I was showered and dressed. I'd had a fairly grim day, huddled up for warmth in the bed, alternating between fitful sleep and laying down trying to stop the room from spinning. From all the sleeping, I'd slightly rebounded and didn't feel like the picture of death anymore, and while I was still feverish I could at least move about. I had a bunch of masks in the bag as well as my meds. The walk to Shibuya Station was hard - it's a ten minute walk on average, which would be no worries otherwise but was very difficult in my current condition, especially with the stairs. I was feeling very rough, and went back to sleep as soon as we sat down on the subway. That would be a pattern for me over the next week or so; falling asleep as soon as I wasn't actively moving.</p>
                        <p>Steph nudged me awake as we got to Tokyo Tower, exploring the shopping complex as we had a bit of time to spare. Steph was hungry, and there were plenty of food places - but I had completely and utterly lost my appetite with my virus. She was keen to try takoyaki, which were balls of octopus in batter. I had no appetite, but lowered my mask and tried to taste one - and I'd lost my sense of taste. Steph ate solo while I tried to stay awake, then we headed up to the tower.</p>
                        <p>The view from Skytree is simply incredible. The city stretched out into the furthest distance, and was already lit up with bright, vibrant colours even though the sun had just set. I couldn't imagine many other cities that look better than Tokyo when lit up at night. We could see the bright spots of Shibuya and Shinjuku as well as several landmarks, like the Diamond and Flower Ferris Wheel over by the harbour and what I thought was Tokyo Tower but Steph wasn't sure. Tokyo is often seen as a city of highrises, and it obviously is, but quite a lot of it is smaller buildings - suburban-style houses surprisingly close to the city centre as well as schools and smaller districts. Every bit of me ached and wanted bed, and every shuffling step I took was painful, but the view was utterly amazing.</p>
                        <p>We left after about an hour, me falling immediately asleep on the subway back. On the way back, Steph suggested an excursion for tomorrow in case I couldn't manage a day in Tokyo. One of the ones she found was the Hitachi Seaside Park excursion. It included a trip to the Ōarai Isosaki Shrine and the Nakaminato fish market. The selling point was that I could fall asleep on the bus for almost three hours on the way. I felt guilty about being ill and on a bus full of people, but I rationalised it - I might not be contageous, I'd be wearing a mask all throughout the journey, and everyone else in the last few months had saw fit to travel with anything from a minor cold to full-blown COVID.</p>
                        <p>Therefore, I reluctantly agreed, hoping that this was a 24 hour bug and I'd feel better in the morning. We showered and went to bed, me falling asleep within seconds.</p>
                    </div>}

                    <div onClick={expandDay5} id="day5ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 5</h4>
                        <h5 className="dayLocation">Hitachi Seaside Park</h5>
                    </div>

                    {day5 &&
                    <div className="days" id="day5">
                        <p>I woke up feeling almost as rotten as yesterday. I say almost, because I know that if the excursion had been booked yesterday, even the threat of a hefty nonrefundable reservation wouldn't have got me out of bed. As it happened I was able to drag myself out of my sickbed, kicking and screaming all the way, pleading with poor Steph to find some way to cancel.</p>,
                        <p>Alas, there was none. We'd lose way too much money for no good reason if I couldn't drag my skeleton up. We headed to Tokyo Central Station, finding the right bus after about ten minutes of frantic exploration. We got into a couple of seats and, yes, I fell asleep within about thirty seconds. By the time I woke up we were about two hours into a two and a half hour drive. Not only that, but were far away from Tokyo, into the wide open. One thing I'd been key to see was the real, rural Japan, the side that most tourists will never see. We were on a motorway, but I was still excited. I felt much better after a long morning nap, though I was still far from my best.</p>
                        <p>What was more, Steph was excited. Unlike me, she loved excursions, and didn't mind the time-restricted nature of the day. In just over half an hour - for which I danced in and out of sleep - we arrived at Ōarai for the Ōarai Isosaki Shrine. It was called a city, but it was really a small town with a threadbare - but lovely - main road. We parked outside the entrance to the shrine itself, which unlike the others we'd seen which were squared-away compounds, this one extended from the main shrine site, down some strairs past the main road and all the way to the sea. My legs immediately croaked as I walked, and the pouring rain didn't do much to improve that, but the nap had done me good.</p>
                        <p>We crossed the road, following a narrow path to the shore, where, over a concrete seawall, we saw the very end of the shrine - a single Torii gate, perched onto a rock about twenty metres into the water. It wasn't as grand as some we'd seen at Senso-Ji, and if it had been painted originally - it wasn't clear - it'd had long been completely stripped off and the gate was now grey. But it looked really cool, some sort of spiritual gateway in and out of Japan. Apart from the beautiful gate, the rest of the scenery was very pretty, but the concrete wall - and the rain - almost reminded me of the UK. We had forty five minutes so we had a walk. The other occupants of the bus, who were all Chinese, decided to go straight back to the bus - I have no idea why. Having observed them on mass over the course of those two weeks, I concluded that they go places more to tick it off and say they've been rather than any actual enjoyment. I'd never travel if I didn't enjoy it.</p>
                        <p>We explored the main road, with charming wooden buildings and some more modern shops and places. We stopped off at a nice looking hotel to get some coffee and check out the view from the panelled windows. We sat in the dining room staring out onto the rocks, and I don't know what it was about the decor, but it also sort of reminded me like an old hotel or cafe in an English seaside town. But it was a nice place and the view was lovely. We headed back, getting temporarily lost and being a couple of minutes late to the bus, something that would be a bit of a theme for that day.</p>
                        <p>Our next stop was Nakaminato Fish Market for lunch, and Steph was practically mouthwatering at the prospect. Unfortunately for me, my appetite was still completely nonexistent. As we expored the single road that comprised the market, Steph grabbed loads of small bites, one of the main stars being hand-shucked oysters. Near the end of the road there was a conveyor belt sushi bar tucked neatly at the back of a wholesale fishmongers, and boy do I regret not having an appetite for this place. Steph ate her fill while I think I had a small sashimi and a matcha or something similar. Then we went back, me heading to the coach as I was feeling rough, Steph down the other end of the road for a smaller fruit market.</p>
                        <p>I had time for a bigger sleep on the way to Hitachi Seaside Park itself, which we got to after around an hour's drive. It's a curious place. On the one hand, it's not too dissimilar from a seaside theme park back home, with rides, arcades, and stuff to eat. On the other hand it also has so much more, like huge flower gardens of amazing regional and seasonal favourites, lots of green space, and an ampitheatre. Being late May/early June it wasn't exactly the start of the season yet, and the place was more or less deserted. Steph went to find a toilet and I explored the amusements. They had a small selection of games, all of them classics - basketball, skeeball, and a shooting range. I headed straight to the shooting range and got given these little corks which I loaded onto the airgun. I don't know why, but that first try was all it took, though the magic never came back. On like my third shot I hit the major bullseye, and got given a selection of prizes. I chose one pillow-sized toy that looked a bit like Pikachu's face. Steph burst out laughing when she saw me with it; she'd only left me alone for five minutes.</p>
                        <p>We walked around and played more games, enjoying ourselves. Unfortunately none of the flowers were really in season, but we walked around and found our way to a surprisingly large ampitheatre on the other side. I have no idea why it was there, but I assume they have summer concerts or something when the place is in season, which is insanely cool.</p>
                        <p>I slept the duration of the trip back, waking up when we'd got into the city proper. I'm glad I slept, because it gave me enough energy for our evening plans. My birthday present from Steph had been dinner at Fushikino, a delightful Michelin-star restaurant in Shinjuku that offered a kaiseiki meal (lots and lots of plates) with a sake pairing. We'd been really looking forward to it, though I was worried about my appetite and being in a place where I couldn't wear a mask. I felt a pang of guilt of possibly infecting people (in case I was contageous, or still contageous after a couple of days) but we couldn't cancel without losing lots of money and for the last four years so many people had been walking around and eating dinner with open symptoms, so I can reconcile that slightly ethics-wise.</p>
                        <p>It was a beautiful place, small and minimalist, but it's the kind of sleek traditional minialism that stands for pure class. The waitress was very nice, and I hope I didn't give her a bug. We tucked into, I think, around eleven plates, and even with my appetite and my taste buds suppressed I couldn't describe them as anything other than delicious. We started off with abelone, watercress and asparagus, then moved onto shrimp dumplings, abrame and red snapper, grunt fish that had been dried overnight, swordfish, several different platters of wonderful seafood and shellfish, and miso. Each of them were expertly paired with a delicious sake. Of the eleven dishes, I was starting to seriously struggle wtih fullness. But by the middle of the course, the chef had come to watch us eat. You're really supposed to fawn over the food and proclaim that it's the best thing you've ever tasted when the chef comes to inspect you, which was not a tough sell for either of us. The chef seemed delighted im a stern way, and there was lots of mutual bowing at the end of our meal.</p>
                        <p>It was our last night in Tokyo (well, until the return leg) and in any other situation we'd have made use of the time as it wasn't that late. But I was on death's door, and we were both incredibly full after the keiseikei, so we went to bed.</p>
                    </div>}

                    <div onClick={expandDay6} id="day6ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 6</h4>
                        <h5 className="dayLocation">Tokyo to Kyoto</h5>
                    </div>

                    {day6 &&
                        <div>
                            <p>I woke up slightly improved from yesterday morning, but still feeling mostly like death. Today we'd be taking the Shinkansen, the bullet train, from Tokyo to Kyoto. It was scheduled for 5pm so we still had more or less a full day in Tokyo. We decided to start our day with what we'd originally planned for day one - the Dawn Avatar Robot Cafe, a cafe where you're served by robots. I was pleased to note that my fogginess diminished quickly once I was up and about, but it never went away entirely.</p>
                            <p>We got to the Dawn Avatar Robot Cafe. It really is a very cool place. The guy who runs it was a Hikikomori, which if you're a normal person won't mean nuch to you but in Japan's youth culture (and internet culture in general) a hikikomori is someone who seals themselves in their bedrooms for long periods at a time, having no social interaction and getting completely immersed in anime, games, or something else. It's a sort of cry for help against what is often quite a grim future for Japanese teenagers, a life of sixteen-hour days and <i>karoshi</i>, which is basically summarised as 'death by overwork'. Most kids go through their hikikomori phase for a few months or a year at most, but this guy was hikiko for <i>four years</i>. That's like a sentence of solitary confinement.</p>
                            <p>But what he did at the Daw Avatar was nothing short of amazing. He turned his own experience and thought of an idea for people who are lonely and isolated to both engage with people and get paid for it. The robots are piloted by these people from afar and they talk to you while you're eating and drinking, and everything is translated. We started off with a girl who had some rare syndrome, then the poor thing got too nervous and disconnected, and we talked to another woman. She didn't seem hard up for companionship, and she'd seemed to live an interesting life. She'd once bussed it from London to Edinburgh in what sounded like an amazing period of travelling, and had seen quite a bit of Europe. But she had to go speak to another table, so we ended up making conversation with a British (by way of South Korea) guy who was nearing the end of his travels. Steph ordered a snack but I stuck with coffee, my appettite not quite having come back. We wished him well and headed out. We still had quite a bit of time so we decided to go to one place that had consistently made us happy in Tokyo - Akihabara.</p>
                            <p>Akihabara is an amazing place to spend time at. We hit the department stores again, and this time I was keen that I wanted to buy some playing cards. We headed to the place that had had Yu-Gi-Oh cards, as I wanted to buy some. I realised that the cheapo ones in the cases were actual individual cards, but I stil brought some and they're still in the study to this day!</p>
                            <p>Next we hit the amusements, having an awesome time on the shooters and the beat machines. By mid afternoon we were making our way back, getting to Tokyo Central Station in enough time for the Shinkansen. Steph, in addition to maxing out her navivgation skills, had also maxed out her observational skills to contact Kloot, the booker, to make sure that we had the correct station as it wasn't particularly clear on the ticket. Soon we were settled into our seats and on the way, the train picking up high speed as soon as we left the station. But it's not like we were shuddering along the line; the train is so sleek and so stable that you don't feel a thing as you shoot past the countryside, the quickness of the view being the only thing to remind you that you're ginog incredibly fast. The scenery was very nice, but - quite involuntarily - I fell asleep very quickly. Steph stayed awake, hoping to catch a view of Mount Fuji at the 42-minute mark, which unfortunately she wasn't able to see due to the visibility The other reason was of course the slim possibility of missing the train, which I wish I could say had gone through my fever-addled ind as I slept.</p>
                            <p>One good thing was that we didn't have our suitcases with us. Japan has a world-class baggage delivery service that we used several times across our trip. Our cases had left from the hotel before we'd left and would be joining us in Kyoto tomorrow. The guys who operated the services had really cool green uniforms that were always meticulously pressed and smoothed. If it was in the UK, it would be run by white van men smoking fags as they threw the suitcases into the loading area, smashing anything valuable inside. </p>
                            <p>As it was, I woke up some time before Kyoto, enough to see us pull into Nagoya, a fairly major regional city. From there it was only around half an hour to Kyoto proper, and we got out and headed towards our new accomodation.</p>
                            <p>I'd expected Kyoto to be a lot quieter than Tokyo, and of course it was, but the station wasn't. We jumped on a bus to our hotel just as it was getting dark, and we realised that the hotel was part of the Teramachi Shopping Arcade, a major covered shopping area bustling with people. It seemed to have everything, and I imagined it would be quite hard to navigate. We checked in and were given a room on the ninth floor, which to us suggested 'room with a view'. Ours was called something different to the other rooms on the floor, which were numbered; I think it was called the kabuki room or similar. It was considerably bigger and better than our hotel in Shibuya, but that wasn't the selling point - the decor was amazing. The room was accented by red lanterns and pleasant wall paintings, and the screen in front of the window resembled an Edo-era painting. The room looked clean and the bed looked comfy, and that was perfect for us.</p>
                            <p>We also checked out something that the receptionist had mentioned, which was the reading room on the second floor. This was a really cool area that I would have spent so much more time in if we were on a longer holiday and spending more time in Kyoto - and if I could read Kanji. Because while there were English books, the main attraction of </p>
                        </div>}

                        <div onClick={expandDay7} id="day7ExpanderMorJpn" className="headings">
                            <h4 className="dayHeader">Day 7</h4>
                            <h5 className="dayLocation">Kyoto</h5>
                    </div>

                    {day7 &&
                        <div>
                            
                        </div>}

                    <div onClick={expandDay8} id="day8ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 8</h4>
                        <h5 className="dayLocation">Kyoto</h5>
                    </div>

                    {day8 &&
                        <div>
                            
                        </div>}

                    <div onClick={expandDay9} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 9</h4>
                        <h5 className="dayLocation">Kyoto</h5>
                    </div>

                    {day9 &&
                        <div>
                         </div>}

                         <div onClick={expandDay10} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 10</h4>
                        <h5 className="dayLocation">Kyoto to Sapporo</h5>
                    </div>

                    {day10 &&
                        <div>
                         </div>}     

                         <div onClick={expandDay11} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 11</h4>
                        <h5 className="dayLocation">Sapporo</h5>
                    </div>

                    {day11 &&
                        <div>
                         </div>}

                         <div onClick={expandDay12} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 12</h4>
                        <h5 className="dayLocation">Shikotsu Toya National Park</h5>
                    </div>

                    {day12 &&
                        <div>
                         </div>}

                            <div onClick={expandDay13} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 13</h4>
                        <h5 className="dayLocation">Sapporo</h5>
                        </div>
                        
                        {day13 &&
                        <div>
                         </div>}

                            <div onClick={expandDay14} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 14</h4>
                        <h5 className="dayLocation">Shinjuku City, Tokyo</h5>
                        </div>

                        {day14 &&
                        <div>
                         </div>}

                            <div onClick={expandDay15} id="day9ExpanderMorJpn" className="headings">
                        <h4 className="dayHeader">Day 15</h4>
                        <h5 className="dayLocation">Home</h5>
                        </div>

                        {day15 &&
                        <div>
                         </div>}
                            
            </div>

            <h3 onClick={back}>Back</h3>
        </div>
    );
    }