import './style.css'

export default function America2019() {

    return (
        <div>
            <div id="america2019Box"><h4>Intro</h4>

<p>Me and Steph both enjoy planning our holidays out. We shop around for deals, find the best hotels within a certain range, and have a good idea of exactly what we want to do while we're there. America took this tendency and dialled it up to eleven. We booked the flights to San Francisco back in January and have spent the last seven months obsessively searching, booking, and researching. When the big day came, it was almost surreal, and it didn't really sink in (for me at least) until midway through the flight. </p>
<p>We've both been to the States before, of course. I've even been closer to California, spending some time in Oregon and Washington in the northwest in 2009 and Las Vegas in 2015. Steph has been to New York with her family. The first time I went to the country, I knew I wanted to spend more time there. My stag do to Vegas quenched my thirst, but while Vegas was a fantastic ride, I was still craving something more. I wanted what the Pacific Northwest had given me: true Americana. The big cities, the tiny towns, the dense forests and the endless highways, and all the stuff we never get in the UK because it's a tiny, flat, cold, misanthropic island. </p>
<p>We had an epic journey ahead of us. Starting in San Francisco, we were going through Yosemite National Park, Los Angeles, Las Vegas, the Grand Canyon, back west to Death Valley, up to Lake Tahoe and finally back to San Francisco for the flight home. It was a complete loop that would take us to three states (California, Nevada, and Arizona) and encapsulate over two thousand miles – well over, as it turned out, but more on that later. </p>
<h4>Day 1 - San Francisco</h4>
<p>The last time me and Steph visited the Americas, the travel was a hellish ordeal. We visited Havana via Montreal and Toronto, two cities on the exact opposite side of the continent, in a total flight and layover time that must have gone over 20 hours. This time, it was the opposite – eleven hours, direct from Heathrow to San Francisco, taking advantage of the time difference to arrive at around midday with a whole afternoon to explore. </p>
<p>The flight was quick and efficient, and while United don't have the best or most current films, I did manage to catch two I'd been waiting to see. Jordan Peele's Us was spectacular, and Vice more than justified the hype. We landed on-time and quickly. </p>
<p>The speedy entrance to America came to a shuddering halt when we got to passport control. We stood in the queue for over an hour and a half, steadily losing the will to live. By the time we'd picked up the hire car (a lovely silver Ford Fiesta that served us better than any faithful steed for those thirteen days) time was getting on, and by the time we'd arrived at the Airbnb it was after half four. </p>
<p>It was a gorgeous little house in the Balboa Park district, on a surprisingly steep road named Howth street. The owner, Spencer, was all charm when he greeted us and showed us around what was probably the nicest place we stayed in all trip. A natural host, Spencer couldn't have been a better welcome wagon for San Francisco. He was also, and this had piqued my curiosity even when reading his Airbnb bio months earlier, something of an enigma. He was a clearly religious man with an accent that was hard to pin down but sounded southern, leading me to conclude that he was living far from where he'd grown up. He gave off the impression of being a family man, and his Airbnb profile had a woman in his picture (most likely a wife, from the context) and co-host profiles for his grandsons, though for the two days we were there we never saw anyone else and whenever we ran into him he was always alone with the rest of the lights in the house off. If we'd been there for longer, I would have tried to wrangle a life story out of him, but we had limited time and sights to see. </p>
<p>After we got our bearings, we headed straight down to the Balboa Park BART (Bay Area Rapid Transit), because there's no reason an underground system shouldn't remind you of the Simpsons) to head into town for a look around and something to eat. We wanted to hit up the Mission District, the historic heart of San Francisco's Hispanic population, praised as a hipster culture zone with murals, excellent Latin food and a community vibe. It wasn't that, exactly, or at least not the bit that we visited. The place was full of the homeless and sketchy-looking people selling tat from roadside stalls. It was an eye-opening experience; I'd thought San Francisco outsourced all its social problems across the Bay to Oakland. But we found a great place, which had actually been recommended to us by someone in that epic queue for passport control, called Limon Rotisserie. I had seafood, but Steph had a roast chicken which looked and tasted incredible. </p>
<p>After we ate, we headed slowly back to the BART and then back to Howth Street. It was getting late, and we had plenty to see in the morning. It had turned cold by the time we got back to Balboa Park, and we were feeling the tiredness. Steph had slept slightly on the plane, but I hadn't, and had been up now for just about twenty-four hours. It was time to crash out, sleep the sleep of the dead and get ourselves ready to explore. </p>
<h4>Day 2 - San Francisco</h4>
<p>I'd like to tell you that I took advantage of the superbly comfortable bed and got a great night's sleep ready to face the day. This would be false. I woke up at around 1am after having slept for around three hours, eventually resorting to the drowsy cough medicine we'd bought in a Rite-Aid. I went back to sleep with enough time to not be completely shattered, and as a bonus, I'd disturbed Steph's sleep too. So all good. </p>
<p>It was just as well that I wasn't that tired, because today was the day as far as ‘Frisco was concerned. We were off to Yosemite the day after, and in order to get there before the park numbers reached their peak we were setting off at 5am. This meant a 9pm bedtime (for Steph at least) and precious few hours to see everything the city had to offer. We had one more night in the city at the end, but we had a feeling that after a long drive from Lake Tahoe we wouldn't be able to do much sightseeing. So today was the day. </p>
<p>We headed straight for the Balboa Park BART, taking it to Civic Centre/UN Plaza, which was a short walk away from the famous Painted Ladies. A famous and colourful row of houses overlooked by the equally famous Alamo Square Park. </p>
<p>They were very pretty to look at, but we didn't have long. We hightailed it back to Civic and got some brunch in a mall food court. I had clam chowder for the first time in years (ten to be exact, unless you count the crap you boil yourself from Waitrose, which I don't) and Steph had a lobster roll. After we ate, we took a bus up to the north side, where the world-famous Lombard Street was waiting. This beautiful road is known for being windy and picturesque, and minus the hundreds of people vying for photographs, it was true.</p>
<p>Once we'd made our way up and down the road, taking photos from every conceivable angle, we took a wander over to Steiner Street, home of the famous Mrs Doubtfire house. I can't remember the film very much at all, much less the architecture, but the film was very pretty, and we weren't the only tourists that took a keen interest. Brits, no less.</p>
<p>After we left the house, we took the bus to one of our mutual expected highlights of the day, the Golden Gate Bridge. The most impressive landmark of the city, at least as far as popular culture was concerned, the bridge was one of the things I'd been dreaming of long before we took the trip. We were going to walk across it, stand hundreds of feet up in the air, and get an unforgettable vision of the Frisco Bay, including Alcatraz. There was one problem, however. </p>
<p>We knew that San Francisco was famous for its fog. Bay-based group Train has a song called When the Fog Rolls In named after this quite curious weather pattern, and San Francisco must be the only city I've been to where clear blue skies can be only a mile away from chilly overcast fog. When we'd boarded a bus back in Pacific Heights I'd been reapplying suntan cream, but once we arrived, I was reaching for my jumper from my rucksack. The fog worsened as we got further along the bridge, to the point where I could barely see the water below me yet alone across the bay. What I saw what quite impressive though, and it was clear that we were up in the gods. It was also clear that the bridge was a masterpiece of American ingenuity, something designed to show of the absolute best of human accomplishment. </p>
<p>We didn't go too far across the bridge. The day was getting on, and we had plenty to see. We were keen to get out of this oppressive fog and get to the other thing we were most excited about, which was Pier 39. This pier, which was the most impressive part of the famous Fisherman's Wharf, is a Mecca of shops, attractions and food. We went to a magic shop and saw a pretty interesting trick, before seeing a great trick show near the end of the pier. Life was good. </p>
<p>But the sun was starting to set, and we had to get on. Our last stop was Chinatown, another famous neighbourhood, for a bite to eat before we turned in for an early night. I wanted to eat; Steph was still full after her clam chowder in bread, but I had a feeling I'd be hungry soon. On the way, I convinced Steph to stop at one of the city's dive bars for a quick beer. San Francisco is ridiculously posh and gentrified in most places, but the bars look like something out of a gritty movie. I don't know if it's intentional – hipsters love edge – or whether this was just one part of hip new San Fran that belonged to the downtrodden, but I wanted in. We looked around and settled on a cramped, dark little place (they were all dark) with only a couple of tables and the whole place sitting up by the bar. One of the regulars latched onto me and told me a lukewarm Irish joke that she laughed riotously at. She was a little touched (in the head I mean, not at my gesture of pretending to laugh) but not a malicious sort.</p>
<p>We didn't end up eating, and what's more, we were utterly unimpressed with the look of Chinatown. While Mission Row had been sketchy as anything, it still had a positive vibe to it, whereas this place was just shabby and run down. We headed back, wanting to catch Spencer one last time as we were going to be leaving at 5am, but it appeared he'd gone to bed. We'd had an amazing day, and had seen more or less everything we'd needed to, but it still felt strange saying goodbye to San Francisco so soon. </p>
<h4>Day 3 - Yosemite</h4>
<p>We left San Fran more or less around the time we'd wanted to, sleepy beyond measure but rearing to go. We managed to see Spencer (I'm still guessing as to his sleep patterns) on the way out but had left him a note anyway. We took the Bay Bride into Oakland, which was originally where we were going to stay. The little we saw of it convinced us it was a bad idea. But we were out of town soon, straight onto the road and the beautiful Sierra Nevada mountains. It was what I'd been longing for – that great American expanse, loved by great thinkers from Kerouac to Bryson. Only in America can you drive on the same road for 200 miles without turning so much as 45 degrees, and while the drive from San Fran to Yosemite wasn't as epic as the 395 going south, it was still a great baptism for the open road. </p>
<p>We arrived in Yosemite a little after half nine. I'd been told that the park's main entrance gets </p>
<p>ridiculously congested around that time, and that like Dubrovnik, they close the gates if too many people get through. We didn't quite see that many cars, and the place opens for 24 hours now, but we were still glad to be there early. What followed was a couple of hours' worth of misadventure. </p>
<p>We breezed right past the visitor centre in search of our first hike, only realising about twenty minutes later that we couldn't make sense of the map and had absolutely no idea where to go. So we drove back, spoke to a park ranger, and decided to head to the visitor centre where we could head towards El Capitan rock, or any one of the amazing hiking trails that made the park so famous. On the way, we stopped at a bunch of vantage points, looking out and taking pictures of the beautiful scenery. But by the time we'd got our bearings, found the visit centre, and parked, it was after eleven. Having not eaten anything, we were starving, so we headed straight to the restaurant and had a burger and chips each. By the time we finished up, spoke to another guide and chose a trail, lost and subsequently found the correct car park, it was after midday and had shot up to 35 degrees. I could barely function, and while Steph was doing marginally better, we weren't ready for a hike. </p>
<p>But we decided to push on anyway, and decided on a reasonably easy trail around the almost-certainly beautiful Mirror Lake. We got around a mile and a half in before giving up the ghost. The walk back wasn't easy, and I'm surprised I didn't lose more body weight in pure sweat. We were on our last legs when we got to the car, and headed straight out of the park minus a couple more vantage points. Yosemite is a beautiful place, a forest of beautiful sequoias and redwoods surrounded by rocks, mountains and waterfalls, but by the time we left it, we were barely able to enjoy it. Still think fondly on it, though. </p>
<p>One of our last stops before we left the park was one of the most enjoyable. It was a small beach overlooking a beautiful lake. Other than a handful of French backpackers it was completely uninhabited, and after a hot day walking in the sun I was just itching for a cool swim. The water was freezing but I took to it reasonably quickly, swimming quite far out and diving underwater. It was amazing – here I was, relaxing in perfectly blue water so pure you could drink it, surrounded by some of the best scenery America had to offer. I'd had an incredible time ever since I got to San Francisco, but this was one of a handful of moments that will stick with me forever. </p>
<p>Once I'd had my fill of swimming we headed out of the park and to our accommodation, which was in a small town by the name of Bridgeport. I'm not sure why it was called that – it had neither – but it was a real slice of backwoods. We weren't staying in the town proper, and by ‘the town' I mean the row of shops and houses on either side of a highway that marks every small town in the States. I feel as if American town planners believe that side streets are the exclusive rights of cities; if towns need to grow, they simply expand and spread across the highway, or diagonally if there's an intersection. Most don't, of course; it feels as if they've occupied the same surface area since their inception. I think part of that is that they subsist on a staple of three businesses; motels, diners and grills, and sporting goods stores, provided your sport is hunting or fishing. Some of these towns have nicer places to eat and gas stations, and some of the larger ones have pharmacies or retail parks. But I can almost personally guarantee that if you drive through a small town in California (probably America on the whole as well) you'll find your pick of motels, greasy food places, and sporting goods stores. </p>
<p>With the inclusion of our Big Meadow Lodge (which lay just outside of the main drag) and a couple of nicer-looking places closer to it, Bridgeport had all three of these. We arrived at the lodge just as the sun was setting and looked upon what was probably our worst digs for the holiday, minus one incredibly redeeming feature, which I'll touch on shortly. The ‘lodges' in question were red brick (that is, bricks with a garish-looking red paint cover) sheds with corrugated iron roofs. The division between the tiny bedroom and the tinier bathroom didn't extend to said roof, which really highlighted how ramshackle the place was. It was also teeming with a variety of insects, and generally made the seedy roadside motels we'd seen by the oadside seem like miniature Hiltons by comparison. Add to the mix a friendly receptionist who nevertheless reminded me of the banjo kid from Deliverance and it was starting to feel like we were in a hillbilly horror film. </p>
<p>Speaking of said receptionist, it was at Big Meadow that we ran into our only accommodation issue. We thought we were heading straight from Bridgeport to LA the next morning, and were prepping ourselves for a long drive. But according to our rustic friend, we were booked in for two nights, and when we checked the Airbnb confirmation it appeared we weren't booked in until two days hence. As it turns out, we hadn't been charged for the second night, and the clerk was happy to cancel it. What we were left with was an opportunity to spend the night wherever we wanted, provided it wasn't too expensive at short notice and it lay between Bridgeport and Los Angeles.</p>
<p>But that was a question for later – food awaited. We got into town just after sunset and settled into the bar and grill for a beer and a bit of dinner. The place was pleasant enough, We felt as if we'd earned both after our short but strenuous hike, and after a cold one and a burger each we were feeling very settled. We headed back, only to get stopped by a cop after less than ten seconds! We froze – Steph especially – but it turned out he was just putting our lights on for us. I don't think we've ever laughed so hard. </p>
<p>We got back to Big Meadow and the stars were absolutely incredible; they served as the redeeming feature I mentioned. They filled the night's sky, stretching off into the distance, the meagre light offered from Bridgeport doing nothing to dim them. One regret I had from America was not taking enough time to look at the stars, and tonight was the start of that – after a long day we were just too tired to sit out. </p>
<h4>Day 4 - Bakersfield</h4>
<p>After a good look at the cities and towns on offer for our missing night, we decided on Bakersfield. It was a choice between that and Fresno, two lower-league cities that would bridge the gap on a long drive between Bridgeport and Los Angeles, which would have otherwise been over six hours. </p>
<p>I'd wanted to go to Bakersfield because I thought it was the birthplace of the Hells Angels, the original One-Percenter gang. The term, which I explained to Steph with some glee, refers to a comment made by some motorcycling bigwig that 99% of bike riders and clubs were completely law abiding hobbyists. The remainder, who lived avowedly illegal lifestyles (fights with other gangs, meth distribution, etc) proudly clung to the notion that they were the remaining 1%. I'd been fascinated by these groups ever since reading Hunter S Thompson's Strange and Terrible a couple of years back. </p>
<p>But the Hells Angels weren't from Bakersfield – they were from San Bernadino, but they were stuck in my mind as being from Bakersfield because of a bloody shootout they'd had with another MC there quite recently. A sterling reason to visit the place. </p>
<p>We'd found ourselves a cheapish motel in the city last night, and left quite early. We stopped off for breakfast in Bridgeport, seeing the place one last time, and we noticed that there was a large Trump 2020 sign some redneck had put on the side of his house, coincidentally (or not) the side facing the Mexican restaurant we were eating at. It gave us the first real taste of how divided America, and especially California, was. We'd just come from San Francisco, where someone with so much as a small Republican bumper sticker would be tarred and feathered, right into a right-wing heartland.</p>
<p>We had one stop before we hit the open road, and it was one I was particularly excited about. We were going to visit the historic ghost town of Bodie. We took a half-hour detour down a ‘road' that was leading us to the town. It was a road in name only. It was unpaved, and was composed purely of dust and rocks that made the car shake and shudder when we drove above a few miles per hour. But our destination was more than worth it. </p>
<p>Bodie had grown up as a prospecting – and later mining – town during the gold rush, but slipped into decline in the late 1800s. A fire wiped out three quarters of the settlement, but the remaining quarter is perfectly preserved as a Wild West ghost town. It's like Sergio Leone's personal heaven – ancient wooden and faded brick buildings that made up what was evidently quite an advanced town. It had all the things you'd expect from a former prospecting town – a church, a saloon, a hotel, a general store, a brothel – but there was also the things you wouldn't quite expect unless you got into the history of the Old West, such as the remnants of a Chinatown. It was a great place, the American equivalent of Ephesus or some other ruins of a bygone civilisation. </p>
<p>We were just about to get on the road proper, but we had one thing we'd been itching to do ever since Yosemite. We'd seen sparkling, beautiful lakes all the way through, including near Big Meadow, and there was nothing we wanted more than a swim. I'd been able to swim in the beautiful, clear blue waters of the park itself yesterday, but Steph hadn't had the privilege. Besides, it was boiling. We drove past a few lakeshores before settling on one beachy area that jutted into its lake like a peninsula. The place had a marina with a few boats on one side, and a clear patch for swimming on the other. I crossed over to the marina centre to check we were alright to swim, and found an office and a little café, but the place was abandoned. Another car, a family, had also parked up and were swimming around fifty yards away, so we decided to go ahead. </p>
<p>A couple of things put us off. Firstly, the water was freezing, and not in an it's fine, we'll get used to it way like the lake yesterday. Secondly, we were wading out on a gentle concrete slope surrounded by jagged rocks. And thirdly, we saw two dead fish laying at our feet. We headed out quite sharpish, drying off in the sun and heading on the road. </p>
<p>After the lake, we started on the long road. It was still a long trip – just under five hours – but would be the essential bridge of the gap before LA. It was a beautiful drive, from start to finish, and we were once again nestled in the beautiful Sierras. It was also a very straight drive. The bulk of our trip was on Interstate 395, which we managed to be on for 180 miles. Even driving from Oregon to Washington, even driving on the 101 up the coast, I'd never been on one road for so long. It's roads such as these that mean you can drive between American cities that are, say, the distance between London and Edinburgh, and get there in a couple of hours. </p>
<p>When we weren't driving on flat ground for untold miles straight, we also encountered some elevation as the roads criss-crossed the mountains, including some parts that were reminiscent of the opening scene of the Shining. All in all, it was an amazing drive, and Steph distinguished herself for her easy command of the highways. </p>
<p>We arrived in Bakersfield just after dark. It was more or less what I'd taken a guess at – a city you drove through on the way to something better. It didn't look as slummy as Oakland, but had no discernible charm or culture to distinguish itself from the other small cities in the area. We checked in to our motel, which was better than the area suggested, and our focus turned to food. We'd not had a single bit of veg with our meat and carbs over the last few days, and our guts were definitely crying out for something wholesome. So I got a couple of entries on the salad menu at a Wendy's, and while mine tasted like actual human vomit, we felt better for getting a bit of roughage inside us. It was time for a nice long sleep in our twin double beds before the last leg south tomorrow. </p>
<h4>Day 5 - Los Angeles </h4>
<p>We didn't get some cliché intro to the city, seeing its majestic skyline from the highway. We were only aware that we were technically in the city because of the roadsigns and because the traffic had suddenly picked up. We passed by Panorama City – birthplace of the legendary Hopsin – and kept on going until we got into Hollywood proper. We saw signs for the Hollywood Bowl, and saw one of the statues that marked the entrance, and then the city just appeared before us. </p>
<p>Our first stop was Van Nuys, home of the Instagram-famous Birriera San Marcos, a Mexican cantina that's known for its tacos cooked in broth. It was delicious, a great introduction to the city. After we ate, we headed up to La Brea to our Airbnb. </p>
<p>There was one problem – I was absolutely busting for the loo. I'd been busting before we got to Van Nuys, I was busting when I found out the cantina didn't have toilet facilities, and I was busting on the way to the Airbnb. With traffic backed up, and our destination a good distance away, I did the unthinkable, the thing that we'd only been brave enough to joke about in the buildup to our trip. I peed in a cup. </p>
<p>It was a coke cup from our trip to McDonalds. We didn't have much else, and my need was dire. I peed in the cup in busy traffic, praying that no one took too big a look through the window. Steph was laughing her head off, as I'd be doing if the situations were reversed, and we arrived on South Citrus Avenue with an embarrassingly full cup of human urine. </p>
<p>The place itself was beautiful, a Spanish Revival type home in the leafy suburb of La Brea. The owner was a harmlessly eccentric older woman by the name of Irene who welcomed us in easily. Her place was gorgeously furnished, but at the same time it was a tip; it was being redone, and rather than stop the Airbnb cash flow she'd decided to lower the price. </p>
<p>Irene was nice enough, and talked us through the essentials of the property and the area, but all I could think of was the full cup of piss in the car. I went to collect it – discreetly, of course – when we grabbed the bags, and carried it to the toilet where I disposed of the foul waste. We kept on talking to Irene, who told us that we weren't the only guests in the property, and that as the other couple were honeymooners, she'd given them the double bed. What we had were two single beds, tiny and styled like the cots you get in a barracks. That wasn't a problem in itself, but what did pose a problem was Irene's policy of no locked doors. </p>
<p>I'll tell you this plain out – I like being able to lock up. I like being able to lock up when I'm going out, and while I never would have got into this if Steph's family didn't make a point of it, I like locking up once everyone is in the house for the night. Locking up the house is fine for me when I'm at home, because there's an implicit level of trust between us all – if I lived in shared accommodation and didn't trust my housemates, for example, the lock would have to be on my bedroom door. I like the idea of being able to shut out the world, or at least the people I don't know are on the level. So Irene telling us our bedroom didn't have a lock, coupled with the fact that we had other tenants staying here and no one seemed particularly concerned about shutting the front door (plus one other concern I'll touch on later) was not a good start. </p>
<p>But we made the best of it, and soon we were getting ready to set off for the famous Griffith Park, home to the even more famous Griffith Observatory, which commands views of both the city skyline and the Hollywood sign. The problem was, no one stopped to give LA a proper transport system. We had to board three buses, each of which was particularly awkward about change. I'd had experience of the whole exact-change thing on American buses before, but that was in a small town; this was a big city that really should have had something in place. </p>
<p>We got to Griffith Park with enough time to kill before sunset. The first thing I had to marvel at was the sheer spectacle of the LA skyline. The place was absolutely huge, and from our lofty perch the city seemed to stretch out forever. LA isn't as big as London, but it's absolutely gigantic by American standards, big enough to have other real, designated cities inside it. One thing I also found incredible was the sheer amount of skyline, with around four different clusters of skyscrapers. The Hollywood sign was very prominent too, overlooking the city like some sort of Cristo Redentor of entertainment </p>
<p>We still had a while to go until sundown, so we took a brief walk down to a small bench just lower down from the main observatory. The view was pretty spectacular here too. We headed up and checked out the observatory itself. I was glad we did. The first thing we saw as we entered the grand building was a guide demonstrating a pendulum moving around a pit with degrees of latitude marked. But if you're picturing Poe – I certainly would be – then you should know that the main draw of the piece is actually to prove that the earth is a globe. Obviously that fact is self-evident to anyone with half a brain, but we live in a society where stupid beliefs are becoming more and more mainstream. </p>
<p>The observatory had an awesome collection, from a working Tesla coil to all sorts of planetary infographics. But our main draw was the sunset, and by the time we got back out, the viewing deck was packed out with people watching the spectacle. It was amazing to see the city, and the Hollywood sign, bathed in a golden evening light. We stayed there for around ten minutes, dumbstruck, then took the bus back into town. </p>
<p>It was dark now, but still reasonably early, and we had time to kill. I was keen to check out the famous Sunset Boulevard, home of dozens of cool bars and restaurants, including the world-famous music venue Whisky-a-go-go. The neon scenery was impressive, but hiskey-a-go-go wasn't much to look at from the outside, though you could hear the bass pumping from the inside. What we did find was an excellent ramen place, which Steph had been looking for since day one, and I enjoyed too both for the food and the frozen beer they offered. But the evening was winding down. We had an early start – Universal Studios! – tomorrow, and besides, I had a bad throat and felt myself getting ill. We took a final bus back and crashed out, ready to our early start. </p>
<h4>Day 6 - Universal Studios</h4>
<p>I woke up with a raging fever and a death wish. I kicked myself – any day, any other day, I'd have been able to have a late start and have a bit more of a lie-in. But we'd paid an obscene amount of money for Universal Studios, and getting there any later in the day simply wasn't an option. </p>
<p>There was no doubt about it – Universal Studios was more Steph's special interest than mine. I've never been particularly into rollercoasters, whereas she loves them. It's not the adrenalin or the fear I don't like; I've bungee-jumped and skydived (skydove?) in the last couple of years. I just don't particularly like the nausea, whereas Steph quite enjoys it. I was much more fascinated about the studio tour, where you could see all the classic sets and backlots that had made all the best movies magical. </p>
<p>Bug or not, we had to go, and I raised myself from the land of the dead to get in the car. We parked in a parking lot dedicated to ET and headed through the shops and restaurants that lined the outer-rim of the park. I saw Voodoo Donuts, getting a smug feeling that while the place had clearly become a chain, ten years ago I'd been to the original back when it was a tiny place in Portland, Oregon. I credit it with my taste for bacon and maple syrup. </p>
<p>The first thing we saw on the entrance to the park itself was a model of the Universal globe, the one you see at the beginning of all their films. Then we were in! The place was larger than life, a real spectacle, and we felt very overloaded when deciding what do. Harry Potter won out – another thing that Steph is way more into than I am, but I was more than happy to do it. We got a butterbeer from a little stall; it was sickly sweet to the point of diabetes but Steph liked it just fine. </p>
<p>The whole Harry Potter ‘zone' was a recreation of Hogsmeade, the village in Prisoner of Azkaban. It came complete with stucco snow that looked ludicrous when it was over thirty degrees out, but it was quite a cool effect. There were little shops full of merch, a restaurant in the form of the pub there (the name escapes me) and actors in costume. I found it quite fun. </p>
<p>I have a very mixed relationship with Harry Potter. On the one hand, there's nothing I love more than professing a hipsterish disdain for it, raising an eyebrow anytime Steph or anyone else geeks out too much. On the other hand, I'm the first to admit that the books are an easy, middlebrow poolside read and I've gotten quite a lot of enjoyment from them on beach holidays in Spain. </p>
<p>The knowledge of the lore this gave me made me feel quite nervous about the first ride, which involved the Forbidden Forest, because I know that's where the spiders are. I have a sort of advance notion of when those horrible hairy creatures are going to pop up on screen that I would call a spider-sense if the irony wasn't too strong. </p>
<p>As it goes, I think I picked the perfect moment to close my eyes, before even Steph told me to close them. We know what scares the other (spiders for me and masks, claustrophobic images, and sinister weather patterns for her) and we have an unspoken agreement to make sure our eyes are diverted. The rest of the ride, from the Quidditch to the dragons, was fine, and I quite enjoyed it, rollercoaster or not. It didn't do much for the nausea that came with the virus, but it wasn't as unpleasant as I remembered rides being. </p>
<p>After the Forbidden Forest we witnessed a wand demonstration by a dude that had zero interest in impersonating John Hurt, but it was quite well-done. We headed out of the Harry Potter zone and headed towards the awesome Simpsons area. It had all the famous replicas of Springfield buildings, including a Krusty Burger! We couldn't resist, and soon Steph was chowing down on a real life Krusty burger (I had the Krusty dog as the burger had mayo). Once we were finished, we headed towards what I knew would be a highlight of my day: the studio tour. We were on a…well, I have no idea what you'd call it, but it reminded me of the Dymchurch Light Railway. Jimmy Fallon was our guide (not literally; he was on the screen) but he left most of the explanation to our in-the-flesh guide, Patrick. </p>
<p>I was transfixed at once. We started by seeing the various sound stages, and while these aren't a </p>
<p>huge deal in their own rights, you get quite a strong feeling of sheer mythology when you see the productions each sound stage has done. We saw Alfred Hitchcock's trailer, which I thought was a huge big deal until I saw something more tied into his cinematography later in the tour, before we got out of the main studio lot and out into the backlots, ie sets. </p>
<p>The first thing we saw was a replica of New York (not the whole city; we're talking two streets here) that was used by all sorts of shows and movies, such as Brooklyn 99! It was the kind of all-encompassing set that could have been used on a ‘40s gangster movie or a 2019 epic. Next up was a parade of famous movie and television cars, and while some of these (Fast and Furious, Knight Rider, the Flintstones) didn't really inspire much awe, I was pretty blown over to see black Cadillac from the first Back to the Future movie. </p>
<p>The thing that truly shook me to my core and reminded me that I was in a place that, to pardon the cheesiness, film and television dreams are made, was the so-called ‘European stage'. I learned that this stage, which seemed strangely familiar to me, was used for several movies featuring European towns in a bygone age. Think Boris Karloff and those old Universal schlock horror movies from the thirties. It wasn't until Patrick told us what it had been used for more recently that it all made sense – it was the setting for the Good Place, one of me and Steph's favourite shows. It was amazing to think that we'd seen this set so many times on the screen and now we were seeing it in real life. It set the stage, so to speak, for the remainder of the tour. </p>
<p>The next major set we saw was unlike anything I'd ever come across. It was nothing less than a giant replica of a crashed aircraft, complete with strewn valuables, life jackets, and rusty debris, used in the crappy Tom Cruise version of War of the Worlds. Our guide informed us that planes heading to LAX have actually mistaken the set for a real crash and called it in. As with any tour guide anecdote it's extremely possible that the story is false, but I'd certainly mistake it for a real crash. </p>
<p>Not far after the plane crash set, we went up Janet Leigh Drive, and I knew exactly where we were headed. Something you'll know about me if you're reading this (unless you're a Russian hacker who managed to get access to Steph's laptop) is that I love horror. I am obsessed with every horror genre from masked slasher movies to supernatural terrors. But there's one movie I hold much higher than most, and it's one I credit as being the mother of modern horror (pun intended) even more so than Night of the Living Dead or anything by Tobe Hooper. I'm talking, of course, about Psycho. </p>
<p>Seeing the Bates Motel – and I do, of course, mean the real Bates Motel – for the first time was a moment that will stay with me forever. The complete set, including Norman's mother's house, was there, and the whole sight was incredible. They even had an Anthony Perkins lookalike who chased us with a knife, and it was all very novel. The only thing that detracted from it was the other set in the area, which was a massive construction for Horton hears a Hoo. So my image of the Bates Motel is always hilariously tarred by a giant pink structure rising out the top of it, though it's still pretty amazing. </p>
<p>The last thing that really stuck out on that tour was a huge water set that our guide informed us was used in a very famous film, which was Jaws! At the tail end of our circuit around the lagoon, an animatronic Jaws jumped out at us. I was reminded of the movie Mallrats, where one half the main due Quint describes his dream of proposing to his girlfriend on the ride, at the exact moment "when Jaws pops out of the water". I kicked myself – if only I'd forced Steph to watch more Kevin Smith, that would have been a viable proposal option, and I'd have gone down in Askewverse history. </p>
<p>You see, I had a beautiful white gold and sapphire engagement ring in my suitcase, and if all went according to plan I was going to leave this trip with a fiancée. I'd bought the ring a couple of weeks before we flew after painstaking window shopping and had hidden it in the wardrobe terrified of it being discovered. But I was also incredibly excited, building up to that one moment where I would pop the question. </p>
<p>While I wouldn't have blown our golden moment on a reference Steph wouldn't have gotten, I knew from the start where I would propose. But more on that later. </p>
<p>I felt a lot better in the afternoon, well enough to go on the amazing rides Universal Studios had to offer. There was the Mummy, Fast and Furious, and Transformers, all of which were incredibly fun. </p>
<p>We headed out of the park in the late afternoon and once we'd taken the car back to Irene's, it was time to head back into town. We headed to a spot I'd been quite keen on visiting since the </p>
<p>beginning, which was the famous Santa Monica Pier. It was an incredible place, full of bright lights and people, with fairground attractions that, while not a patch on Universal, were nonetheless very impressive. </p>
<p>We took a walk around the pier, and when we were done, we headed to Second Street to a classic American diner. Weirdly enough, it was the closest we got to an old-fashioned American diner even though it was a hipster place in the big city. Either way, my burger was delicious. We sat out on the pedestrianised street as a street musician played a tune and people hung around to listen, talk, or just enjoy themselves. It was a reminder that, here we were, thousands of miles away from home, in a city that for most people only existed in dreams.</p>
<p>We headed back to Irene's and looked for something to do tomorrow. We weren't done with the studios, and were excited to see a Warner Brothers tour that featured part of the setting of the Gilmore Girls among countless other films. We couldn't wait. </p>
<h4>Day 7 - Warner Brothers</h4>
<p>Most of my illness was gone by the time I woke up the next morning, which was something I was particularly glad about. Today was our last day in LA, and while I was incredibly excited for the exciting next chapter of our trip, I feel our time in the City of Angels was all too brief. The irony was that at three nights, we spent the longest amount of time there, but still. I don't think I would have got much out of a visit to the places Steph vetoed (Compton and Watts primarily) but I definitely think there was more to this city. </p>
<p>We'd decided on Warner Brothers quite late, mostly spurred on by our amazing experiences at Universal. LA had a lot of things that you couldn't find anywhere else but the magic of the movies triumphed over absolutely everything else. I was happy to note that my bug was on the mend, and we got up quite early, ready for our final day in tinseltown. </p>
<p>Much as Universal communicate their prestige by having a statue of their logo be the first thing you see as you arrive, one of the first things we saw at Warner Brothers was the iconic water tower. What's more – and I get excited thinking about this to this day – it was decorated with Welcome To Derry for use in the second chapter of It. But that wasn't the only thing we would see that instantly resonated with us. A couple of years ago, Steph introduced me to the Gilmore Girls, an American show about a mother and daughter living in a small town. I thought I'd hate it, but the truth was I absolutely loved it. We got to see the whole town, with the primary focus being the gazebo in the town square. It was very strange, but incredible at the same time. </p>
<p>Next on the tour were the prop tours, and they were something to truly behold. They had countless bits of memorabilia from, amongst other things, Batman. That's not just cowls and batarangs; every Batmobile, from the Tim Burton original to Christian Bale's Tumbler, was on show, and they were originals, too. We saw props from Harry Potter and other DC movies, including, amusingly for Steph, a model of the giant spider from the third Harry Potter movie. The props were incredibly impressive, the spider aside, but the fun wasn't nearly over. The next stage of the tour was a lot more interactive, and it proved to be the more popular. You could give a fake Oscar acceptance speech, see yourself on Harry Potter's broom, and do a mocap of Dobby the Elf. Of course, Steph was only interested in one thing after that, which was to sit on the Friends couch. Yes, the real one. Even for a non-Friends fan, the effect of sitting on a piece of TV history was pretty amazing. </p>
<p>We headed out shortly after that, because the next stop was the Hollywood Walk of Fame. We had an almost sixth sense about what we would feel about this one, which wasn't a lot. Everyone we talked to said the same thing: it's busy, it's touristy, it has nothing to show for it other than the stars themselves, and really, what are they for? As it happens, we weren't particularly impressed with them, though the whole area was impressive in how touristy it was. I think it must have been the most artificial place in the most artificial city in the world, and somehow, that was alright. </p>
<p>We had two more places to go that I wasn't keen to leave LA without seeing: Beverley Hills and Malibu. In Beverley Hills I was mostly hoping to gawp at nice houses, but there's only so much gawping you can do, because rich people do everything they can to hide their houses from people like us. Malibu, though, was something much more. It's renowned as an ultimate beach town, a paradise for sunseekers, and while television is rarely reflected in reality, we both found it a lovely beach community, with a fascinating small wetlands area to walk around in. It was definitely a playground for the ultra rich, but it was a beautiful bit of coastline. </p>
<p>The day was getting on, and we had an early rise tomorrow, so we headed back to town. We were going to head to Vegas quite early to enjoy the day, and while I was itching to go back to LV, we were both going to miss LA in a big way. It was a peculiar place, and while it hadn't quite made the impression San Francisco had, it really is a place full of magic, if that's not too cheesy. </p>
<p>We headed downtown as there was a taco place Steph wanted to try for dinner, but a queue full of white hipsters snaked down the road, so the place must've been popular. Downtown, by the way, was one of the scariest places we saw on our trip, as it was full of belligerent-looking homeless and dark alleyways. I'd wanted to see Compton and Watts before I came out, which Steph had vetoed, but in the downtown area I felt as if I was getting close to what that actually would have felt like, and I'm entirely certain I wouldn't have liked it. </p>
<p>We looked around for somewhere to eat and fixed ourselves on one place we'd wanted to eat from the outset of the trip: the International House of Pancakes. I had chicken and pancakes and it was absolutely delicious. We turned in not long after that; we could have spent our last evening drinking the night away in some trendy LA dive, but the time for partying was yet to come. And that time was tomorrow. </p>
<h4>Day 8 - Las Vegas</h4>
<p>Of all the times I'd been to America before this trip, my trip to Las Vegas had felt like the least American experience. That's not to say it was a bad experience; on the contrary, it was one of the wildest parties I've ever had, and I'm no stranger to the magic of the place. But on the other hand, it lacked that American quintessence that I fell in love with the first couple of times: that classic American open road, with its small towns, open space, and majestic scenery. </p>
<p>But I will defend Vegas, a city that I should by all rights be sneering at, to my dying breath. Everything its detractors say about it is true: it is utterly without class, culture, taste, or history, and has nothing to offer other than drinking, gambling, and sin. But unless you've been there, you don't understand the sheer appeal the place has, and how anyone can be drawn into the lifestyle Vegas offers.</p>
<p>We set out quite early from Irene's place, getting one final pang for Los Angeles but keen to push on to new horizons. I couldn't tell who was more excited; me, who couldn't wait to see some more of Vegas's charms, or Steph, who had barely placed a bet in her life but who was itching to do so. We headed out of the valley and towards the desert, keen to take in the sights of the Mojave on the way. The Mojave isn't your typical desert, by which to say it isn't miles and miles of sand, like you'd imagine from the Sahara. I'm sure there are parts of it that are like that, but the parts we saw were more like stones and dusty earth. You're never going to see the best of the desert when you're driving along the highway, but what we did see was pretty in its own way. </p>
<p>There was something quite exciting about crossing the state line into Nevada. It wasn't overly-signposted, and if you're expecting a huge sign with the state outline, you'll be disappointed. What there was right on the state border was the town of Primm, a resort town with a huge roller coaster. I knew Primm quite well, as it features quite heavily in one of my favourite Nevada-set games, Fallout: New Vegas. I asked Steph if we could stop here for that reason but it was a firm no on any video game sightseeing, which was fair enough, I suppose. We passed further into Nevada, admiring the scenery, and getting more and more excited as we approached Vegas. </p>
<p>When I arrived in Vegas last time, I came straight in via the airport, so I didn't get a scale of how tiny the city looks from afar. You're always told that there is a city beyond the strip, but when you approach via the highway, it doesn't appear to be the case. You've got a skyline (which, again, is the strip) and apart from that it looks quite sparse. When you're inside, it comes off as a metropolis, but it all looks quite tiny from far away. </p>
<p>It wasn't long before we were inside the city limits, driving down the strip and taking in the sights, from the Mirage to the Luxor. Elvis, you can imagine the song, was blaring in the car and we felt like we'd arrived. We headed down the strip to our hotel, the SLS. I'd never heard of it, but it turns out that it was where the old Sahara hotel and casino. Except it was more complicated than that; turns out the SLS was the Sahara having been rebranded, but it was now being reconverted back into its original name, so technically neither was currently correct. </p>
<p>Either way, the place looked great. The desert heat, which had been beating down on us since when we got out the car, was instantly washed away by the powerful air conditioning that hit as soon as we opened the door. The casino floor was huge, full of tables and gaming machines, and wasn't that busy, which was a plus. What was busy was the check in desk, and we were early for check in anyway, so we decided to hit the tables. </p>
<p>Time passes ridiculously fast when you're gambling in Vegas. It's designed to; that's why the casinos don't let in any natural light or have clocks on the walls, so you have no idea what time it is in relation to when you arrived. But even if the casinos weren't all up to this trick, there is no other way to kill time quite like at a blackjack or roulette table. Your body keeps you pumped with dopamine every hand you win, you're chatting easily to other people at the table, and the waitress brings drinks round on a perfect schedule: frequently enough for a pleasant buzz, but not enough to get you smashed. All in all, it's quite an idyllic existence while you're there, and if you gamble reasonably responsibly it's no more harmful a vice than having a couple of glasses of wine of a weeknight.</p>
<p>I like to think that I'm a somewhat seasoned, if not necessarily skilled, hand at poker, blackjack, and roulette, but Steph was brand new to each. She never really took to blackjack, but hoo boy, did she take to roulette like a duck to addictive water. Never have I seen someone go from rank amateur to seasoned pro at something so quickly – it was like walking past a park where some boys are playing football and seeing the least-coordinated one magically turn into Mo Salah. </p>
<p>As we played, we chatted to the other players and they marvelled at our journey thus far. Vegas is an incredible place to make friends, and in a way, it's where America goes to do away with its </p>
<p>division and baggage. Boomer and millennial, black and redneck; you see people getting along great when normally there would only be hatred. I was also very surprised about one thing in Vegas – it was the only place where our accents got noticed. Before we flew, I was saying to Steph that while people in small towns will go crazy about our accents, and possibly to a lesser extent in San Fran and LA, no one will care remotely in Vegas because there are so many Brits there. The opposite was the truth. In small towns from California through to Arizona, people didn't blink when they heard us talk. One person didn't realise that England and the UK were the same place, but even he seemed nonplussed. Vegas? That was the opposite. People seemed genuinely fascinated to hear about our trip, and we seemed to make friends at every table. </p>
<p>We could have honestly stayed there for ages, but I'd just made us break even with a few choice bets (I should point out that Steph did so two after, before she kills me) and we had a few stops to make. We headed to the main end of the Strip, where two of the most famous hotel and casinos, Caesars' Palace and the Bellagio, were. I'd done both before, but I didn't want Steph leaving Vegas without having done so. I also wanted to go to Treasure Island, which looked cool, but we never got around to it. </p>
<p>We moved from Caesars' to the Bellagio and then onto Paris, but didn't stay in any of them for long as we didn't like the look of the tables or their limits. Plus, Paris didn't like our IDs. Our only pre­arranged stop was the Linq casino, which was where we'd booked to do a zipline over the Strip! Not just that, but we were doing it Superman style, flat on our stomachs. As we waited to be strapped in, it looked like an incredible distance to fall, so we were both somewhat nervous. But once we set off, it felt incredibly exhilarating, and as I watched the people down below I felt as if I was actually flying. It was absolutely a thrill ride. We are narrowing down on our adrenalin kicks in the last couple of years – bungee jumping for both of us, skydiving for me, and now altitude ziplining. Anything else, from base-jumping to wingsuit-gliding, was a bit too dangerous and/or extreme for us. </p>
<p>After the adrenalin wore off, we grabbed a spot of dinner on one of the pedestrianised streets just off the Strip, finding a seemingly chain restaurant that was a strange fusion of Mexican and Japanese. I had a sushi burrito, which was a burrito with the wrap being replaced with rice and nori. It is one of the most inventive bits of fusion food I've ever seen. As we ate in the outside dining area we people-watched, and watched Vegas flow by. Everyone was drinking, laughing, having fun. There was a vibe here that we hadn't experienced anywhere else on our trip, something intangible, something great. </p>
<p>We headed back to the Sahara (it was our favourite casino so far, and we were only upstairs!) for some more gambling. We played roulette, drank and made friends until around two in the morning, when we finally headed to the room and crashed out. Viva Las Vegas. </p>
<p>Day 9</p>
<p>Las Vegas </p>
<p>Ah, day nine. What can I say about day nine? </p>
<p>I guess I could start by saying that we woke up the latest of any day in America, just after ten. We were tired, and more than a little hung over, but ready for our last proper day in Vegas. We headed over to the Stratosphere for a delicious breakfast buffet, which wasn't on the top floor, but was excellent. I had two ideas for what to do. The first was a shooting range a few miles north of Vegas; it was a local one, not a tourist one that charged through the nose, but it was vetoed by mutual consent as it was too far and we didn't have enough time. The next was the mob museum, which was mutually vetoed because it was nearly forty dollars, though I regret that since recently when I learned that Frank Cullotta, who was key Vegas mobster Tony ‘The Ant' Spilotro's right hand man, who was a key figure in Nicholas Pileggi's book Casino and who was played by the legendary Frank Vincent in Scorsese's film adaption, was one of the tour guides. I learned this fact rather recently after finishing Pileggi's aforementioned true crime masterpiece and looking up Cullotta, the only key figure during the mob's 1970s heyday still drawing breath. I had visions of taking his tour, asking him a million questions before coaxing him about for a beer afterwards so I could hear all the stories he didn't get time to tell on his tour. Don't get me wrong; La Cosa Nostra were and are a bunch of monstrous killers, and Cullotta confessed to some serious crimes while probably doing far worse. But I've had an obsession with mob history ever since I saw Godfather I for the first time, and to meet </p>
<p>and hear stories from a real-life Mafiosi would have been one to remember. </p>
<p>But, as I stress, I found this all out long after the fact. If I'd known before, I would have pushed the issue. As it was, I agreed it was bit too much money and we headed back to a casino, where we at least had a chance of winning some back. The day was a blur of gambling after that, but there was one more thing to distract us from the tables: Penn and Teller! I'd been a fan of the two master magicians for a while, and had managed to convince Steph that they would be a better show than the Blue Man Group. </p>
<p>We got a cab to the Rio, an extremely colourful Brazilian-themed casino (though it paid very little heed to the theme; the outside was vibrant, but didn't necessarily remind me of its namesake city) for Penn and Teller's show. I was incredibly excited. I'd been to magic shows before, mostly of Tenerife hotel complex-level quality (which is coincidentally where I'd seen them) but I'd never been to see a proper, bona fide, world-class magician, much less a pair. Steph had shown some interest in Criss Angel, but I opined that he comes across as a complete dick, whereas Penn and Teller are both known for their easygoing sense of humour and their longstanding reputation for exceptional magic. </p>
<p>The pair have their own theatre within the Rio, which overwhelmingly speaks to their status as Vegas legends. When we got in, we were given a cup and two playing cards, which would obviously make sense later. The legendary magicians came out on time, were engaging, and true to form, Teller didn't speak, though my colleague who had been advised me that he does speak when doing a meet and greet, which gives a certain amount of glamour. Oh, you saw them on YouTube? I heard Teller talk. </p>
<p>They warmed us up with a few great little tricks, then they did the interactive trick involving the cards, which we didn't quite keep up with. Then it was time for the heavy-duty tricks, starting with an amazing trick involving cracked glass ‘made' whole again. It all led up to the final trip where an ‘elephant' (really a cow with a plastic trunk) was made to vanish from a curtained box surrounded by audience members. It absolutely sidelined us, and thinking back, I can't even hazard a guess at how they did it. </p>
<p>We met both Penn and Teller at the meet and greet afterwards, and Teller, true to my colleague's advice, did speak to us. Both men were very courteous to everyone despite the huge crowd, and we were left with the souvenir of a photo plus the cup and cards, the former of which is sitting on my bedside drawer as I write this. We grabbed a bite to eat in the in-house restaurant and headed back to the casino, where we spent our last night in Vegas gambling. We went up to the room earlier than yesterday, though Steph went up before me. I stayed behind for around half an hour, playing blackjack and nabbing any comped drink I could get my hands on. Then I went upstairs and crashed out. On to tomorrow – the Grand Canyon! </p>
<p>After two days drinking, gambling, ziplining, eating, and more gambling, it was time to leave Las Vegas. We were headed East, towards Arizona and the most inland part of our tour, the Grand Canyon. We were incredibly excited, and I was even more so, for reasons that will soon become apparent. But before we said goodbye to Vegas, there was one more sight to see: the famous </p>
<p>‘Welcome to fabulous Las Vegas' sign. You know the one. Contrary to what I'd always thought, it wasn't on the desert approach to Vegas – perhaps it had been once? – but was actually in the middle of a busy road just off the strip. We parked up to take pictures with it, and were then on our ways. </p>
<p>The road between Vegas and the Grand Canyon was full of desert. It was a beautiful slice of the South West, which boasts geography quite unlike anywhere else in the United States. Our route had several scenic overlooks and we were at the very top of some seriously high terrain. It was approximately four hours to Tusayan, the small town just south of the Grand Canyon, an incredible distance when you consider it's frequently billed as a Vegas tourist attraction. </p>
<p>The Hoover Dam is on this route, and we were sad to realise we narrowly missed a turning for it. But this was the same way we were coming back, so we resolved to look out for it on the return leg. In the absence of the dam, we had other amazing scenery to look at. We stopped for a couple of the overlook points, and we also stopped at a beef jerky store near the Arizona border. It was a great little place, very quirky, decorated by cartoons. We bought a decent-sized bag of jerky, but didn't eat it until back in the UK a couple of months later. </p>
<p>It was early evening by the time we got to Tusayan and the Red Feather lodge, a pleasantly rustic motel where we were staying. It had a Native American (Apache or Navajo, one of the two) feel about it that was mostly tasteful, and the room was spacious and clean. But we didn't have time to take in our surroundings as Priority 1 was getting to the Canyon in time for sunset. We were against the clock. </p>
<p>Time for something of a reveal here: My original plan was to propose to Steph when dawn broke on the Canyon the next morning. I'd had the image in my mind ever since we planned the trip. I'd kept the ring in my suitcase all this time ready for when I could take it out. Of course, it's extremely unlikely that you're reading this and you don't know the story, unless you're our grandchildren from the future and have stumbled onto this (by now incredibly obsolete) laptop in a box of old things. Then again, you probably only speak Mandarin, so this will seem like gobbledygook to you.</p>
<p>I thought about popping the question at sunset instead, though had initially rejected the notion because a sunset gave the wrong vibe. But it was bearing up to be such a clear, beautiful sunset that I gave a strong consideration to bring it with me tonight. But I desisted, and soon we were speeding off in the direction of one of the many observation points of the Canyon ready to take in a beautiful sunset. </p>
<p>The Grand Canyon is a sight I will never, ever forget. It stretches off, miles and miles into the distance, and all of it is yours to survey. It's absolutely unforgettable, a true wonder of nature, and I feel privileged for having seen it. Down the bottom, hundreds of feet below you, it's alive – the rivers flow and the bushes shake and move in the breeze. It's a world of its own, and you're at the very top of it. I can't talk that much more about the Grand Canyon without slouching into cliché but suffice to say, it's an experience that can't ever be forgotten. </p>
<p>As the sun went down, and the park was bathed in dusk, we sat on a log and just watched in awe. We're both suckers for sunrises and sunsets, but this was one for the ages. We stayed out until it got fully dark just staring out in awe. I have to admit, it would have been a perfect time to propose, but I was just happy to be there. </p>
<p>We headed back to town with some hesitation and made our way out for the evening. Tusayan is one of those classic roadside towns like Bridgeport, except instead of intersecting a small country road it intersects the huge Route 64. It very much styles itself as a pioneer town with wood, or at least wood-façade, buildings. We stopped at such a place, a steakhouse by the name of, uh, the Steakhouse, and helped ourselves to some delicious steak and some local ale. We made it just the one, however, as we were going to have to get up just before five the next day to catch the sunrise in the Canyon. Unbeknownst to Steph, it was going to be a very important day. </p>
<p>Day 11</p>
<p>The Proposal </p>
<p>So, the proposal didn't go exactly as planned. </p>
<p>When we were getting ready at around five in the morning, I took the ring out of the suitcase. The best place for the ring box was in my shorts pocket, beneath my wallet, so it would look like part of the same ‘mass' as the wallet if Steph paid too close attention to my shorts, as she is wont to do from time to time. When the time came, I would have to strategically take both of out of my pocket, then put the ring box on top of the wallet. </p>
<p>We arrived around twenty minutes till dawn, parking up and getting ready to hike the short trail to the best viewpoint. Worried about it dropping out of her pocket, Steph gave me the motel room key, and I put it in my wallet. We arrived at the spot and, to my annoyance, it was full of people. I know Steph well, as you'd imagine, and I know that the worst thing in the world for her would be a big public proposal with around fifty people in attendance, especially Americans, who would lose their mind and be all over us. I panicked, but then we both noticed a small little overlook a few yards down from us. It was a flat overlook that was enclosed by the gift shop, but the gift shop was closed. But there were people still down there, so we traced the path round to a narrow route around the building, blocked by a large boulder. We climbed over the boulder, hopping out on the other side onto the viewing deck we were barely sharing with anyone. </p>
<p>The first rays had spring up over the horizon, and the sun was due up any minute. The time was right, so while Steph checked out the sunrise, I discreetly pulled a switcheroo, taking both the ring and my wallet out of my pocket, and putting the ring above it for easy access. I was all ready to go – before Steph ruined everything in a few words.  ‘Do you have the room key?' </p>
<p>Not a bad question in itself, but at that moment, it ruined everything. Because I'm quite poor at remembering small things, so instead of a confident ‘yes, of course I do, you gave it to me twenty minutes ago, you moron' I instead offered a lukewarm ‘I think so, I think you gave it to me a little while ago, right?' </p>
<p>Instant panic. Steph became convinced the key had dropped out of her pocket while she was scaling the rock, and could not be convinced otherwise. I said I was certain that the key was in my pocket, which was as far as I could take my reassurances at this time, because the wallet I was 80% sure the room key was in was trapped behind a large ring box in my pocket. Eventually, Steph's logical mind overtook her panic button, and she calmed down long enough to demand to see the key if I was so certain I had it. </p>
<p>I got flustered. At this point, my only options were to try to manoeuvre the wallet in such a way I could take it out of my pocket without showing Steph the ring, but I struggle with basic motor skills at the best of times. So I did what any scrambling, panicked buffoon would do, and just flat out said ‘no'. </p>
<p>Red bandanas in Pamplona have had less of an impact. Steph went mad, reasoning that I'd been lying about having the card all along, or simply cared more about winding her up than ensuring we actually had the room key. She demanded to see my wallet two more times. On the second time, seeing that I wasn't getting anywhere, I relented. </p>
<p>‘Fine,' I said, ‘but first…' </p>
<p>I took the ring box out of my pocket and Steph's eyes went wide. She pulled me into a more secluded area of the lookout and I got down on one knee. Well, that was somewhat true; the ground was rocky as hell so I rested the knee about half an inch from the ground. Being born in South East London and not Beverley Hills, I hadn't prepared some major gooey speech, so I opted for a classic ‘will you make me the happiest man in the world'. Naturally, I meant it more than I could mean any cheesy speech, and we were both ecstatic when the answer came back as yes. In all the holidays Steph and I have been on, I've always struggled to pinpoint an absolute high point of the trip, mostly because it's all been so amazing. There wasn't one bit of our America trip that wasn't amazing, but still, I have absolutely no trouble highlighting that moment, with my ring glittering on Steph's finger, the sun just peeking over the top of the hills, at one of the greatest sights of natural beauty in the world, as the undisputable peak of the trip. What the hell? Of all our trips. </p>
<p>Our spirits were ridiculously high, and we were full of questions. When do we tell people? How? When should we get married? What type of do? We made a pact not to tell anyone about our news until we got home; the rest of the holiday was for us, and with the bulk of it behind us, we had to enjoy our time while it lasted. Perhaps running contrary to this carpe diem spirit, the first thing we did when we got back to the motel was take a nap. We'd been up since five for the sunrise, and while I sometimes wake up at five naturally, I was feeling equally exhausted as Steph. So we had a brief nap before checking out of our motel. </p>
<p>We were headed for the town of Beatty, which overlooked one of California's more extreme national parks, Death Valley. The name wasn't the only thing extreme about the park: the hottest place on earth, it once recorded a temperature of 56 degrees, which is absolutely insane. It's also home to a huge number of diverse species of animals, including some fearsome arachnids I was hoping against hope not to run into. It was one hell of a drive from the Grand Canyon, so we decided to find a stop halfway before rolling into town in the evening. Of course, the best waypoint was in fact Las Vegas, and we reasoned that we might as well get some more gambling out of our system while we were passing Nevada. So we decided we'd get a couple more hours at the Sahara before pushing onto our final stop. </p>
<p>As we left the motel and got onto the highway, I felt a pang. I like to call it a Bryson moment: one of my favourite passages of his is in the book The Lost Continent, wherein he details his travels around Europe. It's the very end of the book, when he's reached his most eastward destination, Istanbul. </p>
<p>Before he leaves for the airport back home, he has a wild fantasy of giving two fingers to the arbitrary end of his travels, of crossing the Bosphorus and pushing on into Asia for a longer </p>
<p>adventure, before pushing it down and heading off to the airport. I had that same feeling: we'd </p>
<p>reached the most easterly point of our journey, and while London lay far east of us (or west, if we wanted to take around four long-haul flights) we were going west, to a couple of amazing stops of course, but ultimately back to the airport. I wanted to go east, push through into the Midwest, check out the majesty of the Colorado Rockies or take a historical highway all the way through to the east coast. But it was what it was, and it wouldn't have paid to be maudlin, so I forgot about it as we got on the road. </p>
<p>This time, we were determined to check out the Hoover Dam. We took the turnoff and came up to an incredible scenic overlook, from which we could see both the dam itself and the amazing canyons that make up the American Southwest. The dam itself is incredible, an absolute manmade wonder, comparable to the Golden Gate Bridge but perhaps earning more points due to the wild, mountainous terrain it was built in. If you're there on a daytrip, I think it's possible to take a tour of the dam, but since we didn't have a whole day, we hung out on the scenic overlook for a while and took in the grandeur. After that, it was a quick turnoff back onto the highway, and straight to Vegas for our last precious couple of hours in the casino. </p>
<p>We broke about even, not quite getting into the same Vegas spirit as last time, mostly because our time was immediately finite. After a couple of hours of spirited play on the roulette tables, we headed out of the city and took the northwest road to Beatty. There wasn't much change in the scenery, but one thing that became readily apparent by the highway stores and billboards was that we weren't far from Area 51. As a lifelong UFO nerd, I have always wanted to check out the installation's fences, as well as visit the Lil Ale Inn bar and restaurant which lies right near it. I've also really wanted to check out Roswell over in New Mexico, but that was far too east for us. When I first saw the roadside stores I wanted to find the Inn, but it was too far out of our way. Nonetheless, I enjoyed the tourist stores, and it felt amazing to be so close to a place I'd been so obsessed with. </p>
<p>We got into Beatty around dusk, and were starving. It wasn't much of a town, clearly designed to rake in the Death Valley tourist trade without offering much to its visitors. The best option for dinner was a Denny's we passed on the way to our motel, which was housed inside a hotel and casino that looked somewhat impressive on the outside, but was dinky and sad on the inside. But we didn't care about that too much, we were hungry, and it would have seemed strange to us to have spent so long in the States without going to a Denny's. We were joined (not at our table; that would've been weird) by some biker dudes whom I couldn't tell whether were scary one-percenters or Wild Hogs-style weekend warriors (having read Hunter S Thompson's book about the Hells Angels, I had no desire to find out) but apart from that, most patrons were locals or Death Valley explorers. We were going to head off to bed after dinner, wake up early, and check out Death Valley before the midday sun brought the extreme heat the place was known for. </p>
<p>A long day, all in all. But the best day. </p>
<p>Day 12</p>
<p>Death Valley </p>
<p>Similar to the Grand Canyon, Death Valley can't be done justice on the page. It truly is one of the most amazing places you'll ever see, and while I've added some pictures of it here, nothing </p>
<p>compares to seeing it in real life. </p>
<p>We set off earlyish, wearing the long-sleeve shirts we'd brought for today specifically. The area was covered with clouds, but the sun would still be lethal, and we weren't inclined to have to grow new layers of skin. It was a short drive to the park, during which time we saw the hilly topography of our ride give way to pure, unspoiled desert. It was a perfect remedy to the Mojave, which had been more rocky than the pure sand desert I'd expected. But Death Valley was wonderful white sand abound, and I wish to god all these months later that I'd taken some. </p>
<p>Our first stopping point was the car park for the ranger station, and as we got out of the car, we </p>
<p>were struck dumb by how apt the park's name was. The valley was dead. It stretched out for miles, but in all that space, barely a single sound could be heard. I have never experienced anything like it before or since; prior to that day, the quietest place I've ever been to was the Back of Ardy in Donegal, but that's only quiet as far as human noise is concerned; you can still hear the trees shake in the wind and the calls of birds and sheep. Here in Death Valley, scarcely a hundred yards from an operated ranger station, the air around us was devoid of all of that. In more isolated spots along the road I called out just to hear the echo; it must have been heard miles away. </p>
<p>Our first stop was the park's historic Borax Works, where labourers (mostly Chinese) harvested </p>
<p>borax from the ground. It was hot, heavy work, and I can only imagine how horrendous work it must have been during a plus fifty heatwave. Next on our trail were the famous Salt Flats, a huge area of pure crystallised salt created by the evaporation of a salt lake god knows how long ago. The Flats were located in a point called Badwater Basin, which is the lowest point below sea level in America, which partially explains the heat. Seeing the sign denoting sea level a couple of hundred feet above us really hammered this home, but our main gaze was drawn to the beautiful Flats, which stretched off into the distance. It's an amazing sight, a desert made out of salt, and I'm a little ashamed to say that after feasting on it (not the best move in such a place, but we had water) we took a small amount home with us. We shouldn't have (I was against it, until we did it) and if everyone did what we did, there'd be no flats left, but hey. I'm sure they've survived worse. </p>
<p>Our next stop was a driveby of the famous painted hills. If you have a picture of Death Valley in mind, it probably includes these hills. They manifest as all sorts of different, fantastic colours, from the natural earthy tone of the desert itself to vibrant light blues and greens. They really are a wonder in themselves, a perfect site, and while we still had the sand dunes to go, we knew that was what would stick with us of the day. </p>
<p>The sand dunes were quite impressive in themselves, and fun to be on! It was good to feel the purest sand between our fingertips, not to mention run around after such a long time in the car. After we got on the road again, we didn't have much more time in the park before we had to go to our next, and penultimate, destination, Lake Tahoe. The lake, in addition to having wonderful scenery, was comparable to our trip to Veradero in Cuba; a relaxing waterside stay to wind us down from our travels. </p>
<p>It was still quite a long drive from Beatty to the lake, so we left the park shortly after the dunes and got onto the highway once more. It was a slightly more built-up journey, with considerably more small towns and roadside businesses jotting the way. Some of these small towns were real Deliverance-style backwaters, places you wouldn't want to break down in, peopled almost exclusively by hostile-looking men sat on their porches, staring out at the road. But many had an inescapable charm, that slice of Americana we'd seen in Bridgeport and other stopovers. </p>
<p>By the time we got closer and closer to the lake, our journey had taken a sharp upward direction. We'd steadily been gaining altitude, going from the below-sea-level Death Valley right back up into the Sierras. We were getting more steadily hungry and tired as we got higher, due in part to the altitude, and also purely being worn out. </p>
<p>At the top of our steep climb, we saw an amazing sight, which was the entirety of the lake and the town stretched out in front of us. I wish to god I'd had a chance to take a photo, but couldn't get the angles right. It's an incredible place, this little slice of paradise nestled in the mountains, offering nature and respite in equal measure. When we started our descent it was almost a shame to lose out on that aerial view, but we were keen to see what the place had to offer us. </p>
<p>The town had a classic California-Nevada border vibe, with the establishments on the latter side proudly displaying the right to gamble within. I wondered if there was much competition between the two, but whichever side you were on, the town was beautiful. We found our motel, which was quite rinkydink compared to some of the establishments nearby, but would absolutely suit us. We dropped out bags off and set about finding something to eat. Luckily for Steph, who had missed out on the chance to get proper sushi on her trip so far, one of the best restaurants in town was a sushi place. </p>
<p>I haven't talked about our food much in this journal, which is criminal in some cases, but I couldn't conclude this chapter without talking about this sushi restaurant. The food was incredible, and the fresh seafood sushi was fresh, delicious, and well-made. The waiter couldn't have been more accommodating, even by the service standards we'd experienced during the trip, and we knew very quickly that we'd made our choice well. I also got the chance to try mezcal, an amazing Mexican-American spirit similar to tequila that I'd wanted to try for ages but had had difficulty getting hold of in the UK. Imagine a smoky, mature tequila you wouldn't even dream of ruining by making into a cocktail, and you're there. I tried an excellent mezcal recommended by the waiter, and felt amazing. </p>
<p>We brought some snacks from Subway on the way back to our room (the sushi was incredible to taste, but typically not mega-filling) and crashed out, ready for our last full day in the United States. We were going to have a much-needed day by the lake, then take a final drive over to San Francisco, where our airport hotel and our early morning flight waited. </p>
<p>Day 13</p>
<p>Lake Tahoe </p>
<p>Lake Tahoe is even more beautiful in the day than at night. </p>
<p>We headed out reasonably early, taking in the sights of our slightly elevated position by the lake, before finding a trail that would take us down. It was a great little hike, perfect for breaking a sweat that we would wash away in the lake, but not too exhausting. The lake was surrounded by dense woods, but the tourist trail had been well-carved out. When we got to the beach I couldn't wait to get in the water, with Steph following soon after. It wasn't the same experience as swimming in the lake at Yosemite; there, I'd felt like Teddy Roosevelt or some other outdoorsman getting in touch with nature. Here, there were lots of people around, and I couldn't swim far out. But all the same, it was amazing, and I felt utterly free. I've always felt more at home in the water than land, and it's the only place I don't feel clumsy and uncoordinated, though I probably am. </p>
<p>We alternated between swimming and sunbathing for a while, truly at peace after our exciting adventures, before taking a hike back up. We climbed some rocks and got more absolutely fascinating views, taking in this truly gorgeous, unique place while we could. But we knew we </p>
<p>couldn't linger for long, because it was a three and a half hour journey to San Francisco. We were determined to leave as late as possible, squeeze our last day for everything it had to offer us. But eventually, the afternoon sun started to sink, and it was time to move. </p>
<p>Words can't express how bittersweet that journey to San Francisco was. On the one hand, we were going away from this incredible country, back to the humdrum life of work, Croydon, and home. Our dream holiday, the one we'd been thinking about, planning, plotting, and enthusing about for months, was drawing to a close. It had felt like such a full, incredible trip, but also, it had passed us by all too quickly. On the other hand, we couldn't be too sad: we'd made memories that would be with us forever, and what's more, we'd set the course for the rest of our lives together. Neither of us knew exactly which extreme we should cling to, so we teetered on the edge, trying to burn the beautiful mountain scenery into our minds so it would still be there when we made our dreary commutes to London and our offices a few days later. </p>
<p>The sightseeing part of our journey was over; we'd briefly tossed up a trip into town, maybe to see the Golden Gate Bridge one more time, but neither of us was particularly up for it with the night descending and our bones being tired. But the city (and, I like to think, America) decided out of pity to treat us to one of its best sights: the fog rolling in off the bay. We'd seen this up close of course, but to see it from a distance from our spot on the bridge was something else. You can see this huge, seemingly sentient cloud of mist make its way from the harbour, blanketing everything. It made me think of that Train song I mentioned, When the Fog Rolls In, which is a sad song about difficult goodbyes. It felt apt. </p>
<p>The Crowne Plaza is a typical airport hotels, though it took staying at one to realise that they're literally everywhere. By this time, our bags were so full of stuff, and our bodies so tired, that getting them to the room felt like a Herculean labour. But the room was fine, two double beds (a luxury we'd been getting increasingly used to in the last few day) and a perfect space to get repacked and lament our incoming departure. I slept that night with a pang in my stomach; just like my second and longest trip to America, I really, really didn't want to leave. </p>
<p>Day 14</p>
<p>Home </p>
<p>There really isn't anything to say about our last day. </p>
<p>America had nothing to show us in the couple of hours between waking up and clearing airport security. We grabbed a quick snack, hung out at the airport and left on time. We were in pretty low spirits, knowing that before long we'd be at Gatwick, then the grim charms of East Croydon. To pull up to that flat station, with clouds in the sky and rain splattering down after so much time spent driving in beautiful open California countryside would be too much of a downer. In the few days and weeks after we got back, the post-holiday blues and the ennui would vanish, but until then, we would be left with a bitter reminder of how home paled in comparison to where we'd been. But as the plane took off, I couldn't help but feel optimism creep in. </p>
<p>The first time I went to America, back in August/September 2009, I wasn't that sad to leave, because I already had plans to go back within two months. The girl (well, woman) I was with long distance was happy to have me in her house for much longer, two months, and I was already counting the days until I returned. The second time, that relationship was on the rocks (meaning no more reason to visit, not to mention no money to do so because work wasn't particularly stable for me back in those days) and I'd grown so infatuated with the United States that for months and months after I came back, I had an all-consuming, psychologically damaging fixation with moving there. Essentially, my life after I came back was confusing and chaotic. This time, however, I was in a much better place. I was travelling back with my beautiful new fiancée, to a stable job, and a country that, with the benefit of hindsight, I had no desire to leave for greener grass. So I couldn't be too sad, but it still killed me to leave this amazing country, knowing I wouldn't be back for at least a few years. </p>
<p>I could see something change in Steph too. She'd only been to America once before, to New York, but it had struck her more as a city break and she hadn't quite fallen in love with America yet. California had been a rough compromise. But when she came back, she was much more enthused, and I'm convinced she doesn't want to wait a few years to go back. She even suggested a Vegas wedding. </p>
<p>The first thing we had to look forward to when we got back was telling everyone our fantastic news. Beyond that, we had some scrimping and saving to do, as we would soon be ready to get our mortgage together. So there were exciting things on the horizon – but for now it was time for us to fly, eat, watch movies and sleep. We'd be home soon. </p>
</div>
        </div>
    )
}